### ISSUE TITLE
Keep folds open when staging

### ISSUE THREAD

**Issue by hkupty** [TimUntersberger/neogit#10]
When debugging #7 , I realized Neogit constantly falls back to mode `2` after I stage the hunks. I guess the ideal would be to not revert, since one can probably add another hunk from that same file, for example. An alternative would be to make the behavior configurable.

**Comment by akinsho** [comment]
Just wanted to bump this issue since it's a little old now and this is a daily frustration for me as a new neogit user. If someone wants to point out what would be needed to fix this I can have a look when I get the time/I'm tipped over the edge by my frustration. Alternatively I can wait for a fix if it's better done by someone with know how about the code base

**Comment by TimUntersberger** [comment]
This probably is because we redraw the whole buffer after modifying the status.\

@RianFuro What do you think?

**Comment by RianFuro** [comment]
Yeah that's part of the problem. Another challenge we need to solve is that even if we only selectively redrawing the buffer, we still need to potentially update/replace the diffs inside the folds without breaking the fold itself. Well, or restoring the fold status after a redraw i guess.
I'd like to avoid manually updating the buffer to match the operation result, so we'd need some logic to calculate a delta from the new status (after a operation or reload) against the current one and then redrawing parts of the buffer based on that delta. Think shadow dom handling, basically.

I definitely feel the frustration just as much though :sweat_smile: Going to have a look at that soon-ish

**Comment by akinsho** [comment]
This might be a red herring and I apologise if it is I haven't read through all the code myself, but I think https://github.com/wbthomason/packer.nvim uses nvim extmarks to keep track of items and update each specifically in it's UI as plugins are being updated in parallel, the code is in its `display.lua` module. That might be a useful insight for what you're describing

**Comment by hkupty** [comment]
I think using extmark is the way to go, but from what I remember from the code, it might need a refactoring on how things are presented.

I guess the idea would be to keep track of the state between redraws and take in consideration the previously set fold level on the first pass directly.

**Comment by hkupty** [comment]
Feels like this has been sorted out. I'm fixing it. Thanks!
