### ISSUE TITLE
Integrate gitstatusd

### ISSUE THREAD

**Issue by hnspn** [TimUntersberger/neogit#102]
Large repos are slow
Would it be possible to integrate gitstatusd?
Or any other faster git implementation?

https://github.com/romkatv/gitstatus

**Comment by TimUntersberger** [comment]
I believe there shouldn't be a repo that is slow in the status buffer as long as we watch out for performance. (Monorepos might kill us?)

**Comment by hnspn** [comment]
> sounds like a shellprompt integration,

I thought they had an interface to query the demon
seems like not yet

> Also, could you point me to any open source repository large enough to give us performance issues?

mostly internal repos
could try [LLVM](https://github.com/llvm/llvm-project.git)

it's possible that the size of the repo is not the issue but the filesystem
either way seems like the implementation in gitstatusd is faster
