### ISSUE TITLE
Unpushed commits are in unpulled commits

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#104]
I don't know what happend or what exactly is happening, but my unpushed commits are inside the unpulled changes section.

cc @RianFuro

**Comment by RianFuro** [comment]
Have I mixed those up while refactoring? I'll have a look

**Comment by RianFuro** [comment]
Yeah I totally messed that up. Sorry about that

**Comment by TimUntersberger** [comment]
Unmerged is somehow always empty for me. Does this also happen for you?

**Comment by RianFuro** [comment]
nope. I remember I had that problem while testing, but I believe I had fixed that. At least with my test repo and on `HEAD` this doesn't happen to me.
What does `git log --oneline '@{upstream}..'` tell you?
