### ISSUE TITLE
Slowness related to status refresh

### ISSUE THREAD

**Issue by mhartington** [TimUntersberger/neogit#108]
Recently updated this plugin and started noticing a significant delay related to the status refresh function.
In my testing, if I start nvim in a git repo, cmd-tab to a new app, then go back to my terminal, there's a big delay in any mappings being pressed.  Profiled the behaviour and the results show 

```
FUNCTION  <SNR>47_refresh()
    Defined: ~/.local/share/nvim/site/pack/packer/start/neogit/plugin/neogit.vim:4
Called 1 time
Total time:   0.000117
 Self time:   0.000117

count  total (s)   self (s)
    1              0.000042   if match(bufname(), "^\\(Neogit.*\\|.git/COMMIT_EDITMSG\\)$") == 0
                                return
    1              0.000002   endif
    1              0.000068   lua vim.defer_fn(function() require 'neogit.status'.refresh() end, 0)

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.000117             <SNR>47_refresh()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1              0.000117  <SNR>47_refresh()

```

**Comment by RianFuro** [comment]
I'm currently tackling a problem with responsiveness. Out of interest, could you checkout [`plenary-async`](https://github.com/TimUntersberger/neogit/tree/plenary-async) and see if it improves on that branch? You'll need to have [`plenary`](https://github.com/nvim-lua/plenary.nvim) installed to use it though.

**Comment by mhartington** [comment]
Tested this out but It did not really change things.

**Comment by RianFuro** [comment]
Alright, so we at least know it's not related.

The profiling you pasted finishes in sub-millisecond time btw, so I think you got the wrong invocation there. That being said, the function really only calls git and refreshes the buffer, the latter of which is pretty fast. My only guess right now is that the calls to git are stalled for *some* reason. We do time all calls but don't output that anything atm. I'll change that so you at least have some more information to go by.

**Comment by mhartington** [comment]
So dumb user error on my part, the plenery async branch does seem to work better. It didn't in my previous test because I spelt plenery wrong 🤦

**Comment by mhartington** [comment]
Last note and probably not a huge issue, but the plenery branch does trigger the buffer to scroll back to the top when the refresh happens. Just an FYI

**Comment by RianFuro** [comment]
I am aware, but thanks for the heads-up :)

**Comment by RianFuro** [comment]
Closed with merging my performance improvements. Feel free to reopen though if you find it didn't improve enough.
