### ISSUE TITLE
Error when trying to commit

### ISSUE THREAD

**Issue by hrqmonteiro** [TimUntersberger/neogit#110]
![2021-04-14_11-32](https://user-images.githubusercontent.com/17055027/114728600-9be0b100-9d15-11eb-8831-cc1714ec0f17.png)

**Comment by hrqmonteiro** [comment]
And another one if i try to commit from a file from a lower directory:

![2021-04-14_11-36](https://user-images.githubusercontent.com/17055027/114728863-dc402f00-9d15-11eb-84ad-919012abf594.png)

**Comment by RMichelsen** [comment]
Probably a duplicate of #109 ?

**Comment by RianFuro** [comment]
@hrqmonteiro What OS are you using?

**Comment by RianFuro** [comment]
Closing as duplicate of #109 and #91 respectively
