### ISSUE TITLE
Error on opening ~/.config/nvim

### ISSUE THREAD

**Issue by ddorstijn** [TimUntersberger/neogit#115]
Currently, the following error will pop up at the start if you open a folder with the tilde command in it's name. This is produced by running ```nvim `~/.config/nvim`` 
```
Error executing luv callback:
.../nvim/site/pack/paqs/start/neogit/lua/neogit/process.lua:53: ENOENT: no such file or directory
```

Netrw is disabled, could this be a reason?

**Comment by TimUntersberger** [comment]
Running `nvim ~/.config/nvim` will set the cwd to `~/.config`.

Is this a git repo?
