### ISSUE TITLE
Error when changing fold level

### ISSUE THREAD

**Issue by DonnieWest** [TimUntersberger/neogit#116]
Getting the following error when changing the fold level

```
E5108: Error executing lua ...nvim/site/pack/packer/start/neogit/lua/neogit/status.lua:278: attempt to yield across C-call boundary
```

My Neovim version is:

```
NVIM v0.5.0-dev+1265-g66f9dd3c6
LuaJIT 2.0.5
```

I'm happy to provide any additional information or help with debugging, just not sure what would be helpful from here

**Comment by TimUntersberger** [comment]
This should be fixed in the latest version.

**Comment by DonnieWest** [comment]
@TimUntersberger thanks!
