### ISSUE TITLE
Open/create pull request in browser

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#118]
I'm not sure how well suited this is for neogit specifically but atm I still use a mismatch of tools to handle git in nvim. `fugitive` for diffs which #100 should resolve as well as `lazygit.nvim` but slightly more complex functionality (outside the scope of this issue) one such feature and currently my most sorely missed in neogit is the ability to open or create a pull request for the current branch.

<img width="2029" alt="Screen Shot 2021-04-21 at 11 29 04" src="https://user-images.githubusercontent.com/22454918/115539352-c8a44380-a294-11eb-85f0-9113f092e9b6.png">

`o` in lazy git whilst on the branch will open a new or existing pull request. Since this isn't something that `git` will give you directly. 

I had a look at the source for lazygit
https://github.com/jesseduffield/lazygit/blob/069c7c9d3583c15aea34c08ff7c8be299c94f60d/pkg/commands/pull_request.go#L112-L139

It seems to be possible for a subset of providers which I think is fine for an initial implementation (github,gitlab, bitbucket) and hopefully people can contribute more once the system is in place.

The general idea seems to be essentially constructing and opening a url.

Does this sound like something that could be added to neogit? (Not sure in which popup, maybe the `branch` popup or a new `PR` one 🤷🏿 not sure how this plays with `magit` and what that does?)

PS: I could help try and put this together at _some_ point in the future if there are no other takers/it was my bug bear/granted you approve

**Comment by TimUntersberger** [comment]
Have you looked at https://github.com/pwntester/octo.nvim before?

**Comment by akinsho** [comment]
@TimUntersberger I have actually but `octo` is very specific to github and I work with gitlab and bitbucket from time to time so it wouldn't really be a multipurpose solution. Also I don't really need/want all of the functionality that octo provides just this bit about opening PR urls

**Comment by TimUntersberger** [comment]
@akinsho Until we figure this out you can use the following code in your config.

```lua
local neogit = require 'neogit'
local a = require 'plenary.async_lib'

neogit.setup {
  on_init = function()
    a.scope(function()
      local remote_url = a.await(neogit.cli.config.get("remote.origin.url").call())
      local repo_name = remote_url:sub(16, -5)
      local branch = neogit.repo.head.branch

      local open_pr_url = string.format("https://github.com/%s/pull/new/%s", repo_name, branch)

      a.await(a.scheduler())
      -- on unix
      -- vim.cmd("!open " .. open_pr_url)

      -- on windows
      vim.cmd("!start " .. open_pr_url)
    end)
  end
}

```

**Comment by akinsho** [comment]
@TimUntersberger thanks for the snippet I just tried it out with some tweaking I can't seem to find where `neogit.repo` is though, this field is actually `nil` and I'm not sure what it should be instead

**Comment by TimUntersberger** [comment]
@akinsho yeah sorry. I pushed the commits to the wrong branch. Latest master should now be working.

**Comment by akinsho** [comment]
@TimUntersberger I only changed it slightly because I needed it to work with a gitlab and github off the bat
```lua
command {
    "NeogitOpenPr",
    function()
      a.scope(
        function()
          local fmt = string.format
          local remote_url = a.await(neogit.cli.config.get("remote.origin.url").call())
          local repo_name = remote_url:sub(16, -5)
          local branch = neogit.repo.head.branch

          local services = {
            github = {
              pr_url = "https://github.com/%s/pull/new/%s"
            },
            gitlab = {
              pr_url = "https://gitlab.com/%s/merge_requests/new?merge_request[source_branch]=%s"
            }
          }

          local current
          for service, _ in pairs(services) do
            if remote_url:match(service) then
              current = service
              break
            end
          end
          if not current then
            return vim.notify(fmt("No supported service for %s", remote_url))
          end
          local open_pr_url = fmt(services[current].pr_url, repo_name, branch)

          a.await(a.scheduler())
          if as.has("mac") then
            vim.cmd("!open " .. open_pr_url)
          elseif as.has("unix") then
            vim.cmd("!xdg-open " .. open_pr_url)
          end
        end
      )
    end
  }
```

**Comment by akinsho** [comment]
@TimUntersberger one thing I'd like to add to this is a check to see if the remote branch exists before opening the URL since if the branch hasn't been pushed that has to be done first. `lazygit` uses
```go
// CheckRemoteBranchExists Returns remote branch
func (c *GitCommand) CheckRemoteBranchExists(branch *models.Branch) bool {
	_, err := c.OSCommand.RunCommandWithOutput(
		"git show-ref --verify -- refs/remotes/origin/%s",
		branch.Name,
	)

	return err == nil
}
```

But I'm not sure using the neogit API how to execute that git command

**Comment by TimUntersberger** [comment]
@akinsho added `show-ref` to the cli.

```lua
a.scope(function()
  local branch = neogit.repo.head.branch
  local remote_url = 'refs/remotes/origin/' .. branch
  local cmd = neogit.cli['show-ref'].verify.show_popup(false).args(remote_url)
  local exists = a.await(cmd.call()) ~= ""
end)
```

I set `show_popup` false, because the command will err when the remote doesn't exist and we normally would display the error popup in this case.

**Comment by akinsho** [comment]
Awesome thanks I'll try that out

**Comment by akinsho** [comment]
Actually I think maybe I spoke to soon. Will do some more testing but I think somehow `exists` is always coming back as true 🤔 . Will test some more and report back.

**Comment by akinsho** [comment]
Also regarding this functionality in general I thought I had seen something about it in some Magit videos on youtube and it turns out it was https://github.com/magit/forge which provides this functionality for magit. Tbh that plugin is doing a lot, a lot of which is very cool but I don't know that a whole other plugin is needed for something as small as this. I think if more functionality like this was being added then it might warrant being split of into something separate but doesn't seem to warrant it now.

**Comment by TimUntersberger** [comment]
> Actually I think maybe I spoke to soon. Will do some more testing but I think somehow `exists` is always coming back as `false` 🤔 . Will test some more and report back.

You could manually set the remote url instead of using the actual one if you want to test it.

**Comment by akinsho** [comment]
@TimUntersberger I just ran the command in my terminal e.g. `git show-ref --verify -- refs/remotes/origin/<my-branch>` and that works but I get nothing back via the `neogit` so I *think* maybe it's the implementation of show-ref

**Comment by TimUntersberger** [comment]
Having this function randomly in neogit feels odd tbh. IMO we should just create a new plugin for this. We could then easily provide utility functions like this one. I also want to make the custom keybindings more flexible by supporting functions which could them be used by plugins to "inject" functionality.

**Comment by akinsho** [comment]
Fair enough, was worth seeing if it would be a fit. I was tempted to start something like `neoforge` but I've already got too many plugins on my plate and I'm not sure I've got the time (or will) to create and maintain another. I can close this out  🤷🏾‍♂️ ? 
Think I'll just stick with tweaking the function here or `lazygit`.

**Comment by akinsho** [comment]
Actually been thinking about this for a few weeks and thinking I might actually despite  ☝🏾 maybe look into how creating something like a `neoforge` plugin might work. I'm not sure what that sort of plugin would require need to watch more emacs tutorial on magit/forge, but from a few that I saw it seems like `forge` is able to create or add to the `magits` popups to inject it's own options into certain places.

Would that be something that would be possible @TimUntersberger or that if I fleshed out exactly what was needed (to start) you'd be up for?

**Comment by TimUntersberger** [comment]
> Would that be something that would be possible @TimUntersberger or that if I fleshed out exactly what was needed (to start) you'd be up for?

Not too sure whether it is possible right now, but I would try my best to support someting like this 👍

**Comment by TimUntersberger** [comment]
@akinsho any updates on the `forge` like plugin? Closing this issue, because I think the original problem has been fixed.

**Comment by akinsho** [comment]
> @TimUntersberger I just ran the command in my terminal e.g. `git show-ref --verify -- refs/remotes/origin/<my-branch>` and that works but I get nothing back via `neogit` so I _think_ maybe it's the implementation of show-ref

I think regarding the initial functionality, I stopped at this point since this wasn't working. I'm not sure if it would work now or not after the latest changes.

Regarding a new plugin I'm still mulling it over tbh, I noticed that the commit PR was refactoring some functionality so thought I'd wait and see anyway for that to land. I'm not sure now if I'd be able to use the neogit API to add in a popup to the status buffer or a switch to an existing popup?

**Comment by fnune** [comment]
I use this for this purpose: https://github.com/kristijanhusak/vim-create-pr

(super minimal)

**Comment by CKolkey** [comment]
Glad you said something @fnune - this was very straightforward to integrate. `b o` will use the new `vim.ui.open` API to open the pull request URL if a branch's upstream is configured.

**Comment by fnune** [comment]
Sweet!

`Requires Neovim 0.10.0` :sob: 

https://github.com/neovim/neovim/milestone/36

Really looking forward to it haha :)

**Comment by CKolkey** [comment]
Haha, or nightly builds, of course. The new `vim.ui.open()` api removes a lot of headaches
