### ISSUE TITLE
FEATURE REQUEST; which-key type of cheat on using this tool

### ISSUE THREAD

**Issue by thepenguinthatwants** [TimUntersberger/neogit#121]
Hi,
I know this is not exactly related to the features that this project might be aiming for.

But its often quite hard to remember what each keybindings does. It would be awesome to have a popup reminding what different keybindings does. Especially a type of popup that doesnt disturb the usage.

**Comment by dahmc** [comment]
why did you close this immediately?

**Comment by TimUntersberger** [comment]
@dahmc because this already exists. Type `?` when in the status buffer.

**Comment by dahmc** [comment]
oh, right. Sorry about that ;)
