### ISSUE TITLE
Amending commits causes error

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#128]
**Steps to reproduce**

1. Make any change.
2. Stage it.
3. Open `NeogitStatus`.
4. Press `ca` and confirm a commit message.

You will have an error:

```
Error executing luv callback:
...plugins/opt/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: .../nvim/pack/plugins/opt/neogit/lua/neogit/lib/git/cli.lua:258: E5560: vimL
 function must not be called in a lua loop callback
```

**Comment by Shatur** [comment]
@TimUntersberger, the issue still exists in the latest master.

**Comment by TimUntersberger** [comment]
@Shatur yeah mb! I forgot an if branch. Now it should be fixed completely.
