### ISSUE TITLE
Pressing d causes an error if no item selected

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#129]
**Steps to reproduce**

1. Open NeogitStatus.
2. Make sure that there is no item selected, for example:
![изображение](https://user-images.githubusercontent.com/22453358/118871521-543edd80-b8f0-11eb-88ce-9e59fef875ad.png)
3. Press `d`.

You will have an error:

```
E5108: Error executing lua ...onfig/nvim/pack/plugins/opt/neogit/lua/neogit/status.lua:730: attempt to index local 'item' (a nil value)
```

**Comment by cloggier** [comment]
Not sure if related but I am getting `E5108: Error executing lua ...k/packer/opt/neogit/lua/neogit/integrations/diffview.lua:56: attempt to index field 'diff' (a nil value)` when I press `d` on any files from `:Neogit`.
