### ISSUE TITLE
Commits are incorrectly highlighted in Log popup

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#134]
When opening a log of the current branches commits the commits are not completely highlighted. I don't know if the regex only highlights up to a certain number of characters or what else might be happening

![image](https://user-images.githubusercontent.com/22454918/120679875-92600380-c491-11eb-96a8-15a61141af77.png)

This is hardly blocking just opening it so it can be tracked.

**Comment by TimUntersberger** [comment]
Ah yeah. Currently we only highlight 7 characters.

This should be fixed once #131 is merged.
