### ISSUE TITLE
Plenary error after latest upgrade (June 12th, 2021)

### ISSUE THREAD

**Issue by nobleach** [TimUntersberger/neogit#140]
When launching NeoVim, I'm getting:

```
Error executing luv callback:                                                                                                                                                                                        
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...nvim/site/pack/packer/start/neogit/lua/neogit/status.lua:290: attempt to index field 'repo' (a nil value)
```
This results in a completely empty status view. I am in a valid Git repo. I'll do more digging.

*Edit - updated to latest HEAD of NeoVim 0.5 and made sure plenary was updated. Same error persists

**Comment by TimUntersberger** [comment]
I pushed an update that might fix this. I can't really reproduce this so this is more a guess than anything.

**Comment by paulo-santana** [comment]
It worked. The message is gone and the plugin is working fine agian.

**Comment by nobleach** [comment]
Yep, fixed it for me. My apologies for the lack of information in my original issue.
