### ISSUE TITLE
Commit extend fails silently

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#141]
Hi 👋🏾 ,

I think since the fixes to commit amend, haven't got the commit hash to hand right now, but commit extend now seems to fail silently i.e. it doesn't extent the previous commit it just does nothing. There is no error in the log as far as I can see.

**Comment by TimUntersberger** [comment]
Is the git commit command in the history?

**Comment by akinsho** [comment]
@TimUntersberger it appears as though nothing is actually happening i.e. there are no new git commands. So I think nothing is being executed.

**Comment by TimUntersberger** [comment]
Should be fixed in the latest version.

**Comment by akinsho** [comment]
Yep that's sorted it 👍🏾 thanks @TimUntersberger
