### ISSUE TITLE
Branches sorting by latest checkout

### ISSUE THREAD

**Issue by timsofteng** [TimUntersberger/neogit#144]
Hey! Is it possible to sort git branches by time of latest checkout into it?

**Comment by TimUntersberger** [comment]
Do you mean the autocompletion?

**Comment by timsofteng** [comment]
> Do you mean the autocompletion?

Completion is necessary as well but no I mean sorting. Try to use `lazygit`. Create several branches and checkout to the las and. And then to last one. You will see sorting orged by last checkout in list of branches.

I believe in current realization it could be implemented with popup or with `telescope`. E.g you are in command line then press some keybinding which open telescope popup. And on enter it return branch which user need.

But the main question is sorting.

**Comment by timsofteng** [comment]
Hello!
Any news about this feature?

**Comment by TimUntersberger** [comment]
> Any news about this feature?

I haven't worked on this yet, but I am willing to accept any PRs.

**Comment by timsofteng** [comment]
@TimUntersberger unfortunately I'm not good in lua.
It something like additional option to `git`.
Additionally it would be cool to have alternative to `:G branch` in `fugitive` to see all branches and checkout between them.

**Comment by timsofteng** [comment]
@ten3roberts Do you think it is completed? How can I sort branches by last checkout?

**Comment by CKolkey** [comment]
Sure :)

```
 -- Value used for `--sort` option for `git branch` command
  -- By default, branches will be sorted by commit date descending
  -- Flag description: https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---sortltkeygt
  -- Sorting keys: https://git-scm.com/docs/git-for-each-ref#_options
  sort_branches = "-committerdate",
```

Field names are here: https://git-scm.com/docs/git-for-each-ref#_field_names

But you'll want to use the default value of `-committerdate`

https://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit

**Comment by timsofteng** [comment]
@CKolkey Sorry but I'm not sure I've get what I mean. Commit date and date of last checkout are different things. I could checkout to another branch but do nothing but I expect it on the top of the list.
