### ISSUE TITLE
Git commands silently fail

### ISSUE THREAD

**Issue by itmecho** [TimUntersberger/neogit#148]
When I try pushing to a remote branch that is ahead of my local branch, I get no feedback that this is the case. I think this is happening for most commands that error as I tried rebasing onto a branch using neogit and it did the same thing.

**Comment by TimUntersberger** [comment]
If a command fails you should be able to see the output in the command history.

**Comment by itmecho** [comment]
Ah nice. I think it would be nice to have a notification that it failed in the same way we get the success notification? It's mainly a problem for me as I work on a huge mono repo and the push/pull sometimes takes a while so I never know if it's still pushing or if it failed.

Also I didn't say in my initial comment but thanks for the great plugin! :D

**Comment by TimUntersberger** [comment]
> Ah nice. I think it would be nice to have a notification that it failed in the same way we get the success notification?

If the command returns an error code we actually display a notification, so it is weird that you didn't get a notification 🤔 

What is the return code in the command history? (The leftmost number)

**Comment by itmecho** [comment]
Oh interesting! I'm out at the moment but I'll try and repro it when I get back

**Comment by itmecho** [comment]
OK I can't repro this anymore :confused: Sorry for the time wasting!
