### ISSUE TITLE
Git unstash actions not works

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#150]
**Steps to reproduce**

1. Make a change
2. `:Neogit`
3. `Zz`
4. `Zp` / `Za` / `Zd` - none of the actions will work.

**Comment by n3wborn** [comment]
Same for me (I also have same issue following the same steps he listed).

But I also have this problem about stash feature (but maybe it's related) :

**Steps to reproduce** (NVIM v0.6.0-dev+43-g02bf251bb - neogit bf148e)

1. Make a change
2. `Neogit`
3. `?` (shows help)
4. `Z`

Gives me : 

**E5108: Error executing lua ...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...site/pack/packer/start/neogit/lua/neogit/popups/help.lua:17: attempt to index field 'env' (a nil value)**

Tell me if another Issue is better

**Comment by RianFuro** [comment]
> Zp / Za / Zd - none of the actions will work.

Cannot reproduce that. Note that your cursor needs to be on a stash entry in the status buffer for those actions to work (or even show up in the transient buffer) Are any errors showing up in the command history (pressing `$` in the status buffer)?

> E5108: Error executing lua ...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...site/pack/packer/start/neogit/lua/neogit/popups/help.lua:17: attempt to index field 'env' (a nil value)

Seems to be a regression when triggering stash form the help buffer specifically. Invocations directly from the status buffer should not be affected by this

**Comment by Shatur** [comment]
Tried it again, It was fixed even earlier than ee83d4f. Thanks!
