### ISSUE TITLE
Cannot sign commits with terminal pinentry programs

### ISSUE THREAD

**Issue by LeonGr** [TimUntersberger/neogit#152]
When I try to sign a commit with `pinentry-tty` as pinentry-program I cannot enter my passphrase and the pinentry text looks like this:

![2021-07-01-152917](https://user-images.githubusercontent.com/6065271/124132868-8b70e480-da81-11eb-955d-190230dcc131.png)

**Comment by TimUntersberger** [comment]
I believe this issue is related with #82 implementation wise.
