### ISSUE TITLE
question: how do you use switches

### ISSUE THREAD

**Issue by p00f** [TimUntersberger/neogit#153]

**Comment by clason** [comment]
`<tab>` on the line with the switch -- you can see that the switch itself lights up.

(I guess the basic assumptions is that users of Neogit already know how Magit works; a "beginner's introduction" for people _not_ coming from Magit might be a nice addition to the docs.)

**Comment by gegoune** [comment]
Thanks @clason , didn't know about `<tab>`, was always doing the latter. I, for one, never used Magit before, so would benefit from some additional documentation indeed.

**Comment by clason** [comment]
I just hit a bunch of keys until something lit up 😆

**Comment by p00f** [comment]
Thanks!

**Comment by TimUntersberger** [comment]
> I guess the basic assumptions is that users of Neogit already know how Magit works; a "beginner's introduction" for people not coming from Magit might be a nice addition to the docs

This guy has made a small introduction to neogit. Maybe we can just link to this video?

https://www.youtube.com/watch?v=aJikrPnTOtI

**Comment by clason** [comment]
I'd prefer something I can read, myself... (Ideally from within neovim.)
