### ISSUE TITLE
Too many files error

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#160]
If you have a long session in which you open and close many files, then after a while the `Too many files open` error appears. The error caused by Plenary's async. Similar issue [was in gitsigns](https://github.com/lewis6991/gitsigns.nvim/issues/168) and was fixed after migration to https://github.com/nvim-lua/plenary.nvim/pull/148. It would be nice if Neogit switched to async2 too.

**Comment by AllenDang** [comment]
@TimUntersberger This issue still exists in newest version of neogit.
