### ISSUE TITLE
Trying to open another commit window whilst one is still open errors.

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#161]
Firstly, the commit inspection functionality is awesome 👍🏾, thanks for your hard work on that.
I was trying it out and had 2 commits in the Unmerged changes section and navigated out of the commit window which I left open to open the next commit and got the following error.

```
Error executing vim.schedule lua callback: ...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...im/site/pack/packer/opt/neogit/l
ua/neogit/lib/buffer.lua:113: Failed to rename buffer
```

I would have expected the window contents to be replaced that the old window would have been replaced. In either case, I assume this was an unanticipated edge case, trying to open another commit whilst one is still open.

**Comment by TimUntersberger** [comment]
fixed in latest version.

**Comment by akinsho** [comment]
@TimUntersberger I seem to get a new error with the update `Vim:E95: Buffer with this name already exists`. The steps I took were, use `l` to open the log buffer, open a list of previous commits.
Open the first one in the commit view. Leave that window and repeat. This should reproduce the error.

**Comment by TimUntersberger** [comment]
Fixed now.

**Comment by akinsho** [comment]
Thanks, just tried it out and seems to have been fixed 👍🏿
