### ISSUE TITLE
E5108: lib/popup.lua:95: attempt to call a table value

### ISSUE THREAD

**Issue by gegoune** [TimUntersberger/neogit#164]
After upgrading Neogit  to https://github.com/TimUntersberger/neogit/commit/467d64d8f4e3018a8742aa152ed5e2c83c3bbef0 I cannot open any popups, getting this error message:
```
E5108: Error executing lua ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:95: attempt to call a table value
```

Tried without passing any configuration to Neogit's setup function, made no difference, still errors.
Just upgraded nvim to `v0.6.0-dev+eece0735f`, still the same.

**Comment by TimUntersberger** [comment]
I cannot reproduce this. 

Can you try completely removing neogit and then installing it again?

**Comment by gegoune** [comment]
Thanks Tim, unfortunately that did not help. To give you more input, when I open `:Neogit` and subsequently press 'p' I get:
<img width="914" alt="Screenshot 2021-07-12 at 11 47 45" src="https://user-images.githubusercontent.com/69750637/125258405-fb476080-e306-11eb-81d1-3f3bcc0a4ff4.png">

an empty popup window and error message.

**Comment by gegnew** [comment]
I actually have the same issue :shrug:

**Comment by marcushwz** [comment]
This happens to me as well, but it only happens on a freshly initialize neovim session. After I have loaded a file then it works fine. Not sure why.

**Comment by gegoune** [comment]
For me it happens with loaded file or without.

**Comment by TimUntersberger** [comment]
This is very weird.

@gegoune can you try cloning the repo and use the local version? That is the only difference I can think of.

**Comment by gegoune** [comment]
Just did(90b1901774c11b86f3d36f7d17803125bfbe82b8), also reverted my custom configuration and just called `setup({})`. Removed diffview too - still erroring on any popup.

**Comment by TimUntersberger** [comment]
@gegoune sorry for the inconvenience, but can you try running a minimal vim config? So basically with only neogit installed.

Also which operating system are you using? Does an older nvim version or neogit version work for you?

**Comment by gegoune** [comment]
@TimUntersberger Not an inconvenience at all. Super happy to help. Tried with this minimal config and got:

```lua
local fn = vim.fn

local install_path = "/tmp/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
  vim.api.nvim_command("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end

vim.opt.termguicolors = true
vim.opt.packpath = "/tmp/site/pack/packer"
vim.opt.runtimepath = install_path
vim.opt.runtimepath:append "/usr/local/Cellar/neovim/HEAD-eece073/share/nvim/runtime"

require("packer").startup {
  function(use)
    use { "wbthomason/packer.nvim" }
    use { "nvim-lua/plenary.nvim" }
    use { "TimUntersberger/neogit" }
  end,
  config = { package_root = "/tmp/site/pack" },
}

require("neogit").setup {}

```

```
Error executing luv callback:
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ite/
pack/packer/start/neogit/lua/neogit/lib/git/diff.lua:66: attempt to index a nil value
```
at startup. This is also happening with my regular config I believe.

I know it's not the same error message, an update might have introduced it since my last report.

**Comment by rafamadriz** [comment]
I was having the same issue. Got fixed after restarted I nvim, don't know what triggered that error.

**Comment by gegoune** [comment]
Interesting, restarted all my instances and now I am not getting async error on my regular config but minimal one still errors the same.

**Comment by Shrimpram** [comment]
I'm getting the same error so I did a bit of testing. Plugin works fine until 425d84ce1c3346a5fb47470ee6e2155c7172ff7e, loading 658386fe8bd62a3f4a7c3dcda2dbd1fc251997d4 breaks it and causes the error.

**Comment by TimUntersberger** [comment]
> Error executing luv callback:
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ite/
pack/packer/start/neogit/lua/neogit/lib/git/diff.lua:66: attempt to index a nil value

Added a small safeguard in the latest version. If you encounter an error with the message "TODO: diff parser", please post your `:messages` (the previous message to be more exact)

> I'm getting the same error so I did a bit of testing. Plugin works fine until 425d84c, loading 658386f breaks it and causes the error.

@Shrimpram which error are you talking about?

**Comment by gegoune** [comment]
> > Error executing luv callback:
> > ...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ite/
> > pack/packer/start/neogit/lua/neogit/lib/git/diff.lua:66: attempt to index a nil value
> 
> @gegoune Added a small safeguard in the latest version. If you encounter an error with the message "TODO: diff parser", please post your `:messages` (the previous message to be more exact)

Just updated. Had to make couple of changes to get it to work:
```diff
-      inspect(header)
-      error("TODO")
+      vim.inspect(header)
+      -- error("TODO")
```

and with that I got that header:
```
{ "diff --git a/nvim/minimal.init.lua b/nvim/minimal.init.lua", "new file mode 100644", "index 0000000..e69de29" }
```

this is untracked file if it makes any difference.

**Comment by TimUntersberger** [comment]
> this is untracked file if it makes any difference.

If the file is untracked, why is it then in the diff? Can you paste me the whole diff is possible?

**Comment by gegoune** [comment]
That was the only line printed to `:messages`. 

I just tried different repository and not getting that async error there, but back to
```
E5108: Error executing lua ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:95: attempt to call a table value
```
when trying to open popups.

When I try to get history with `$` it also errors with
```
E5108: Error executing lua .../start/neogit/lua/neogit/buffers/git_command_history.lua:58: attempt to call a table value
```

What else can I check to help identify the issue?

**Comment by TimUntersberger** [comment]
Can you add the following lines [here](https://github.com/TimUntersberger/neogit/blob/b0e218153b0fa80c65cd8a54e09fdfc25f94131a/lua/neogit/lib/popup.lua#L93) right before the return statement.

```lua
print(vim.inspect(text))
print(vim.inspect(text.highlight("TEST"))
```

**Comment by xenrox** [comment]
> Can you add the following lines [here](https://github.com/TimUntersberger/neogit/blob/b0e218153b0fa80c65cd8a54e09fdfc25f94131a/lua/neogit/lib/popup.lua#L93) right before the return statement.

I have the same error when pulling/committing
```
{
  <metatable> = {
    __call = <function 1>,
    __index = <function 2>
  }
}
{
  highlight = "TEST"
}
```

**Comment by gegoune** [comment]
Exactly the same for me.
```
{
  <metatable> = {
    __call = <function 1>,
    __index = <function 2>
  }
}
{
  highlight = "TEST"
}
E5108: Error executing lua ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:97: attempt to call a t
ble value
Press ENTER or type command to continue
```

**Comment by TimUntersberger** [comment]
I found the problem. 

On my machine `vim.deepcopy` also copies the metatable, but it looks like it doesn't work for everyone ?!?!?!?!?

Can you test the following code:
```lua
local tbl = {}
setmetatable(tbl, { __index = { x = 1 }})
print(vim.inspect(tbl))
print(vim.inspect(vim.deepcopy(tbl)))
```

**Comment by xenrox** [comment]
```
{
  <metatable> = {
    __index = {
      x = 1
    }
  }
}
{}
```
Second output table is empty for me

**Comment by gegoune** [comment]
It's the same for me (as per last @xenrox's post) on `v0.6.0-dev+eece0735f`.

**Comment by TimUntersberger** [comment]
Can you check your local vim runtime files? Maybe you are getting a different version on macos.

**Comment by gegoune** [comment]
This is coming from `/usr/local/Cellar/neovim/HEAD-eece073/share/nvim/runtime/lua/vim/shared.lua`

```lua
function vim.deepcopy(orig) end  -- luacheck: no unused
vim.deepcopy = (function()
  local function _id(v)
    return v
  end

  local deepcopy_funcs = {
    table = function(orig)
      local copy = {}

      if vim._empty_dict_mt ~= nil and getmetatable(orig) == vim._empty_dict_mt then
        copy = vim.empty_dict()
      end

      for k, v in pairs(orig) do
        copy[vim.deepcopy(k)] = vim.deepcopy(v)
      end
      return copy
    end,
    number = _id,
    string = _id,
    ['nil'] = _id,
    boolean = _id,
    ['function'] = _id,
  }

  return function(orig)
    local f = deepcopy_funcs[type(orig)]
    if f then
      return f(orig)
    else
      error("Cannot deepcopy object of type "..type(orig))
    end
  end
end)()
```

**Comment by Shrimpram** [comment]
> @Shrimpram which error are you talking about?

The one in this issue: `E5108: Error executing lua ...vim/site/pack/packer/opt/neogit/lua/neogit/lib/popup.lua:95: attempt to call a table value`

**Comment by xenrox** [comment]
I am not a lua expert, but to me it looks like the builtin deepcopy does not copy the metatable: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/shared.lua#L17
A lot of plugins I just looked through (e.g. telescope, snippets) seem to use their own implementation because the original function does indeed not copy metatable: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/_compat.lua#L19
Maybe another plugin you are using is overwriting deepcopy?

**Comment by TimUntersberger** [comment]
> I am not a lua expert, but to me it looks like the builtin deepcopy does not copy the metatable

You are right! I saw the `getmetatable` call and thought they would handle this correctly. sorry! 🤦‍♂️

**Comment by TimUntersberger** [comment]
latest version should fix

**Comment by xenrox** [comment]
> latest version should fix

Looks good on my side, thanks a lot for your work!

**Comment by gegoune** [comment]
Yay, works again! :) Awesome, thank you so much for the fix and your patience with me, @TimUntersberger!

One issue for me though, seems like https://github.com/TimUntersberger/neogit/blob/5cbbfd2d8fdf5cc1651b9b4ad7930d1e30ea056f/lua/neogit/lib/git/diff.lua#L72 is missing `vim.`, had to fix it locally earlier and it errors again after switching to master:

```
Error executing luv callback:
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ite/pack/packer/start/neogit/lua/neogit/lib/git/diff.lua:72: attempt to call global 'inspect' (a nil value)
```

**Comment by TimUntersberger** [comment]
Yeah sorry. This is a function from my own config which I always for debugging and sometimes I forget that it isn't there by default 😆

**Comment by gegoune** [comment]
Ah, sorry, forgot to close it. Thanks for fixing it! It's so amazing to be able to use Neogit again. :)
