### ISSUE TITLE
Cannot write, 'buftype' option is set

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#165]
I expecting the following error message:

```
Error detected while processing BufUnload Autocommands for "<buffer=52>":
E5108: Error executing lua ...vim/pack/plugins/opt/neogit/lua/neogit/popups/commit.lua:39: Vim(write):E382: Cannot write, 'buftype' option is set
```

**Steps to reproduce**

1. Make any changes and stage changes
2. `:NeogitStatus`
3. `cc`
4. `:w`
5. `:lua vim.api.nvim_buf_delete(0, {})`

**Comment by TimUntersberger** [comment]
Wait why are you closing the buffer via the lua API? Does the normal `:wq` not work for you?

**Comment by Shatur** [comment]
> Wait why are you closing the buffer via the lua API? Does the normal :wq not work for you?

Sorry, it from my script. But you can reproduce it with `:bdelete` .

**Comment by TimUntersberger** [comment]
Can you open the commit buffer and then type `:set buftype` what does this return?

**Comment by Shatur** [comment]
> Can you open the commit buffer and then type :set buftype what does this return? It should be empty

Yes, it empty.

**Comment by Shatur** [comment]
Oh sorry, the problem was caused by https://github.com/stevearc/stickybuf.nvim
