### ISSUE TITLE
Git commit put comments in git message

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#169]
**Steps to reproduce**

1. Make some changes and stage them.
2. `:NeogitStatus`
3. `cc`
4. Type any text
5. `:w`
6. `:q`

Your commit name will look in the following way: `asdf # Please enter the commit message for your changes. Lines starting # with '#' will be ignored, and an empty message aborts the commit.`

**Comment by TimUntersberger** [comment]
This doesn't happen for me 🤔

**Comment by TimUntersberger** [comment]
Do you have a commit message template?

**Comment by Shatur** [comment]
Wow, sorry, it also caused by https://github.com/stevearc/stickybuf.nvim
I'm so sorry, will contact the author.
