### ISSUE TITLE
Add top split kind

### ISSUE THREAD

**Issue by jens1205** [TimUntersberger/neogit#170]
Neogit currently defaults hardcoded to "tab" - it would be great if this could be configured.

Additionally, the split is hardcoded to be "below" - it would be great if one could also set it to be on top.

**Comment by TimUntersberger** [comment]
> Neogit currently defaults hardcoded to "tab" - it would be great if this could be configured.

neogit.open({ kind = "split" })

> Additionally, the split is hardcoded to be "below" - it would be great if one could also set it to be on top.

👍
