### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#177]
For reference look at the logging system from telescope.

**Comment by tosiek88** [comment]
Hi I really want to say thank You for your job and effort, I am new to nvim world, working with Doom emacs around 1 year (Mainly Typescript, Go) but unfortunately I am struggle with very slow autocomplete even in LSP mode.  Your plugin is almost same as magit!
Are you planning to make similar log view/layout as in magit (with lines, possibility to switch between branches and commit from this view) . Currently in my case looks like this:
![Screenshot from 2021-08-01 22-07-25](https://user-images.githubusercontent.com/56116159/127784037-b32a325f-496b-4769-aeac-ce65ad6e1c6e.png)

Maybe it's good idea to integrate Telescope with it?

![Screenshot from 2021-08-01 21-53-29](https://user-images.githubusercontent.com/56116159/127783722-3909c2cb-b800-4b38-8632-1a0fe7ecf0bc.png)
Tj has already lines I think this magit/tig way of representing commits are more readable. 

It can be done also as simple alias in ~/.gitconfig
```
[alias]
lg1 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
lg2 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
lg = !"git lg1"
```

![Screenshot from 2021-08-01 22-08-30](https://user-images.githubusercontent.com/56116159/127784019-3b0ed86a-559e-4d27-a90a-91f34ca13018.png)

**Comment by TimUntersberger** [comment]
> Hi I really want to say thank You for your job and effort, I am new to nvim world, working with Doom emacs around 1 year (Mainly Typescript, Go) but unfortunately I am struggle with very slow autocomplete even in LSP mode. Your plugin is almost same as magit!

Thank you

> Are you planning to make similar log view/layout as in magit (with lines, possibility to switch between branches and commit from this view)

This is planned. The lines are low priority.

Regarding telescope integration, please open a separate issue for that.
