### ISSUE TITLE
General slowness question

### ISSUE THREAD

**Issue by gegoune** [TimUntersberger/neogit#178]
Hi, I am not sure how to go around debugging it, but for one of my node (vuejs) projects having neogit starting with nvim causes about four seconds lag on nvim start. So, nvim will start up, no name buffer will show but I won't be able to do anything for about four seconds. This is not the case in other repositories and if neogit is removed.

Additionally I have noticed that neogit takes about 30-40ms on startup regardless. That is if opened without any files in no git repository. What is it doing then?

Thanks for the plugin it's so amazing!

**Comment by TimUntersberger** [comment]
I think this will be easier to debug once #177 is done.

**Comment by gegoune** [comment]
OK, will watch and wait then, can talk about it in due course. Thanks Tim!

**Comment by TimUntersberger** [comment]
@gegoune can you try to reproduce the problem and paste your logs from the `neogit.log` file in the `:echo stdpath('cache')` folder.

**Comment by gegoune** [comment]
I just did, it prints diff commands for bunch of files taking 0 ms each. Timestamp suggests that it's not taking longer than 2s (starts at sec x and finishes at sec x+1). Can paste the log but will have to replace filenames. 

What is puzzling to me is why neogit does that on init? Also the fact that timestamps are not really corresponding with delay I see in nvim, log suggests that nothing takes as long as the delay I see.

**Comment by TimUntersberger** [comment]
@gegoune not everything is getting logged right now, so we will have to build up the logs now to maybe see what is causing the slowness.

**Comment by RianFuro** [comment]
@TimUntersberger from my experience, single very large diffs (about 10k lines in package.lock diffs in my case) are the primary cause of hangs. This makes sense as the whole diff has to be parsed at once and in-sync, since there is no way for the event loop to defer exeuction easily.
I played around with that some time ago, pausing the executing every 1000 lines or so to give the vim core space to breathe, but nothing satisfying came out of that (basically turned a single 3s lag into about 10s of stuttering).
I'm at a loss on how to solve that honestly, since we can't easily spawn a new thread to handle parsing

**Comment by TimUntersberger** [comment]
> Hi, I am not sure how to go around debugging it, but for one of my node (vuejs) projects having neogit starting with nvim causes about four seconds lag on nvim start

@gegoune how are you starting nvim? Are you opening a folder or navigating to the folder after opening nvim

**Comment by gegoune** [comment]
@TimUntersberger I change shell's directory to project's root, then I start empty nvim with `nvim`, without opening any files at start.

Also:
```
$ git diff --shortstat package.json
 1 file changed, 17 insertions(+), 5 deletions(-)
$ git diff --shortstat package-lock.json
 1 file changed, 18603 insertions(+), 559 deletions(-)
```

**Comment by TimUntersberger** [comment]
@gegoune is this issue now also fixed for you?

**Comment by gegoune** [comment]
Yes, it is! Two birds with one stone. ;)
