### ISSUE TITLE
respect git username and password

### ISSUE THREAD

**Issue by lalitmee** [TimUntersberger/neogit#180]
First of all, I would like to thank you for this great plugin for neovim, which is making my life easier a lot.

Recently, I have noticed that `neogit` asks for `username` and `password` for `pushing` the code but it's not respecting
the global config of git in which I have stored my `username` and `password` and it asks for the same thing again and again.

I really want that I don't have to type my `username` and `password` again and again every time I commit and push.

Is this feature already there or not in neogit? If yes, then how I can enable it otherwise what is the roadmap for this?

**Comment by TimUntersberger** [comment]
#172 will fix this.
