### ISSUE TITLE
Gitcommit with custom gitmessage buffer occasionally has the wrong filetype

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#181]
Hey, 

I've been using my custom gitmessage file since you added that functionality, thanks again 👍🏿. I've noticed in the last week or so that occasionally there appears to be a race condition and filetype of my commit buffer is incorrectly set to `conf`.

I've dug a bit into this, and it seems to be happening because vim assigns the `gitcommit` filetype to buffers based on their names

https://github.com/neovim/neovim/blob/93443d59a9680a6055d4602653d34516bc2c2571/runtime/filetype.vim#L656

But since neogit uses a buffer with its own custom name, i.e. `NEOGIT_COMMIT_MESSAGE` `filetype.vim` doesn't assign the buffer it's filetype. I believe this is being set in the `Buffer.create` function in neogit at some point.

https://github.com/TimUntersberger/neogit/blob/bf148e2534097988e61ed334edaf31b67134369b/lua/neogit/popups/commit.lua#L24

The issue I seem to be having is that at some point, not sure when or why this is *I think* not happening early enough and `filetype.vim` is being triggered, and it has a fallback to check for any buffers that start with `#` as the first character of the first line (and some other heuristic) is set to `conf`
https://github.com/neovim/neovim/blob/93443d59a9680a6055d4602653d34516bc2c2571/runtime/filetype.vim#L2333-L2338

Tbh I'm not sure why/when filetype.vim is being triggered before neogit sets the buffer's filetype but maybe the filetype can be set just after the buffer is created but before the content is added to it? not sure if that's just a confusing hack/..fix

**Comment by TimUntersberger** [comment]
> maybe the filetype can be set just after the buffer is created but before the content is added to it?

That is how we do it currently. If you find a way to reproduce this 100% I'll try to fix it.

**Comment by akinsho** [comment]
I'll try and find a way to reproduce it, it's quite common on my setup but a little sporadic 😭

**Comment by captainko** [comment]
I'm having this issue too. My case is that the buffer gets the right filetype (`gitcommit`) but as soon as I switch to Insert mode it's automatically set to `conf`

**Comment by TimUntersberger** [comment]
@captainko can you reproduce this with only neogit installed?

**Comment by captainko** [comment]
I think I solved my issue by removing the line below :(.

```lua
  use {
    "nvim-telescope/telescope.nvim",
    event = "CursorHold", -- <--- remove this line
    cmd = "Telescope",
    --- ...
}
```

**Comment by akinsho** [comment]
I have the exact same line in my config 🤯 , I'll try and remove that and see if it fixes the issue on my end as well. It's *super* strange that lazy loading telescope on cursor hold would cause the commit file to change it's filetype 🤔

**Comment by captainko** [comment]
Yeah, I notice something strange happens to me after adding that line that my cursor jumps to the origin of the file after the CursorHold event fired.

**Comment by TimUntersberger** [comment]
> I think I solved my issue by removing the line below :(.

Good job finding the problem 👍 

I assume I should then close this issue?

**Comment by akinsho** [comment]
Haven't seen it since I removed the line, which makes it a Telescope issue then 👍🏿

**Comment by akinsho** [comment]
So I've had this issue recur several times despite having remove the `CursorHold` autocommand, how about you @captainko is it still resolved in your case?

**Comment by TimUntersberger** [comment]
@akinsho @captainko maybe both of you could compare your installed plugins? It could be that both of you have the same plugin which causes this.

**Comment by akinsho** [comment]
🤔 I can't immediately see any likely culprit, the most annoying thing is that it's quite hard to reproduce since if I could at least consistently reproduce it I could start debugging it 😭

**Comment by captainko** [comment]
For me, there are other plugins causing this problem. @akinsho, you should try to remove some lazy-load events (BufReadPost, InsertEnter, ...).

**Comment by akinsho** [comment]
Hmm having to disable lazy loading on a bunch of different plugins seems strange to me and quite inconvenient since I've had a lot of these setups since before I added neogit, although it does make me wonder if packer might be to blame i.e. maybe it's messing with filetypes when loading certain plugins.

**Comment by TimUntersberger** [comment]
> Hmm having to disable lazy loading on a bunch of different plugins seems strange to me

To be honest this sounds really like it could be the culprit. You can never know what a plugin does on initial load and maybe some plugins interfere/modify the filetype resolution on load? I know it is hard to debug.

**Comment by captainko** [comment]
I have other issues with neogit but I am too lazy to open an issue, so I switched back to fugitive.

**Comment by akinsho** [comment]
@captainko IMO (as a plugin maintainer myself) it's really hard to improve on functionality or fix bugs if you don't know what they are, it helps everyone to have issues reported even if you no longer use the plugin so at least there's visibility and a chance of fixing the issue, just my 2 cents 🤷🏿

**Comment by captainko** [comment]
Yeah because I don't know if it's actually a neogit bug or just my fault :cry:
