### ISSUE TITLE
Add a file to repo

### ISSUE THREAD

**Issue by mangelozzi** [TimUntersberger/neogit#182]
Maybe I am missing the obivous, but have search issues, and gone through the doucmentation options and commands multiple times. 

Say the cursor is over a files listed in `Untracked files`, how does one add that file to git?

I am going through lots of files one at a time, some need to be added, some not.

**Comment by gegoune** [comment]
`s` to stage it.

**Comment by mangelozzi** [comment]
Oh I see, yes obvious now. I have not used Magit before so staging didnt make me click "add".

The best I came up with is `!git add %` after opening it.
Cheers!

**Comment by mangelozzi** [comment]
This plugin is a fantastical blessing! So much faster than using the git command line with aliases. Wow great work! Big thank you! Well done to all the coder(s)!
