### ISSUE TITLE
Allow to stage individual hunks, split, and edit.

### ISSUE THREAD

**Issue by mrswats** [TimUntersberger/neogit#183]
I searched a bit and I could not find anything related to this issue in this repo. I just installed neogit coming from a long period of using fugitive. So far I love it, i love it!

However, one thing I am missing from fugitive is the ablity of staging hunks individually as well as being able to jump to the next hunk and unstaging individual hunks. I also use gitsigns and I can stage hunks that way but I find it a bit clunky to have to go into the file buffer to stage different hunks while I am committing stuff from different files and so on.
Is there a way to do this already?

On the other hand, one cool thing I would love to also have is the ablity to edit hunks directly from the neogit "page" (can't find a better way to describe it) if it is possible.

Thanks in advance and thanks for this plugin!

**Comment by TimUntersberger** [comment]
> staging hunks individually

Hover a hunk and then press "s"

> unstaging individual hunks

Hover a hunk and then press "u"

> On the other hand, one cool thing I would love to also have is the ablity to edit hunks directly from the neogit "page" (can't find a better way to describe it) if it is possible.

What do you mean by editing a hunk? You can go to the file by pressing "enter".

**Comment by mrswats** [comment]
Ooooh, okay, I didn't understand the documentation correctly, many thanks! 

And when you run `git add --patch` you can edit the current hunk (by pressing e) without modifying the file. Is there a way of doing this?

**Comment by TimUntersberger** [comment]
> And when you run git add --patch you can edit the current hunk (by pressing e) without modifying the file. Is there a way of doing this?

No

**Comment by mrswats** [comment]
Would it be something reasonable to ask for?

**Comment by TimUntersberger** [comment]
@mrswats I don't see a point tbh. If you can give me a use case where this is needed I will add it.

**Comment by TimUntersberger** [comment]
@mrswats closing for now. Please open a seperate issue for the editing thing once you have a use case where this is needed.
