### ISSUE TITLE
Git commit verbose not working?

### ISSUE THREAD

**Issue by mrswats** [TimUntersberger/neogit#184]
As far as I understand, the `--verbose` switch should show a diff below the commit message. However, when I try to activate the verbose switch in the commit window I see no change.

Am I doing something wrong or is it a bug?

**Comment by TimUntersberger** [comment]
Fixed in latest version.

**Comment by mrswats** [comment]
Hey, I noticed that it is not working even though I just pulled the latest changes. And I noticed this happening as well for other commands like git push, it does not add the --force flag even though I select it in the window.

**Comment by TimUntersberger** [comment]
@mrswats should be working now.

**Comment by mrswats** [comment]
Awesome, now seems to work.

Thanks!
