### ISSUE TITLE
NeogitStatus empty

### ISSUE THREAD

**Issue by n3wborn** [TimUntersberger/neogit#186]
Hi ! 
It seems like nvim is not happy with todays commits. Trying`:Neogit` or `:lua neogit.open()` result in an empty buffer, as you can see. Could nvim (v0.6.0-dev+153-g2cb8db34e - LuaJIT 2.1.0-beta3), packer and neogit last async2 [commit](https://github.com/TimUntersberger/neogit/commit/da184b2bdbf3e3c5b94da2a4f51400d5b583ab14) be not friends ?

I'm investigating (using git bisect maybe), but I wanted to report this. As usual, thanks for your job :)

![image](https://user-images.githubusercontent.com/10246722/129805798-5b8fea62-9ec6-4035-8eb9-d6a323dc16d3.png)

**Comment by benferse** [comment]
Came here to report exactly this @n3wborn :) I haven't had a chance to investigate yet but can report back if I find anything

**Comment by n3wborn** [comment]
> Came here to report exactly this @n3wborn :) I haven't had a chance to investigate yet but can report back if I find anything

Just currently bisecting, the guilty if after 8a85ef8

**Comment by n3wborn** [comment]
So, for me, last 'good' commit is [](https://github.com/TimUntersberger/neogit/commit/8a85ef8d42e5ee25e281662a6b7e0f6003c7efc8) and so, first bad is [next](https://github.com/TimUntersberger/neogit/commit/d084102aa2bdc9323551026352373abbb8620c43#comments) but not sure the bug is here as this is in the middle of the async2 refac/feature

**Comment by TimUntersberger** [comment]
Fixed in latest commit.
