### ISSUE TITLE
Please read this

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#19]
If you notice a feature is missing, please look for an existing `umbrella` issue and if one exists that matches your request then comment under the issue.

**Comment by winston0410** [comment]
Sorry which issue is the `umbrella` one? I have searched it but no result returned.

**Comment by ibnuda** [comment]
https://github.com/TimUntersberger/neogit/issues?q=is%3Aissue+is%3Aopen+label%3Aumbrella
