### ISSUE TITLE
regression: custom gitmessages no longer appear

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#191]
@TimUntersberger I've recently noted a regression in the custom gitmessages showing up. I believe there was a change that when from reading the gitmessages from the location on the FS to using git commit dry runs output. I might have misunderstood the exact changes but since the explicit reading was removed my custom git commit message no longer appears.

**Comment by TimUntersberger** [comment]
@akinsho does `git commit --dry-run` include your gitmessage?

**Comment by akinsho** [comment]
I just tested it on my dotfiles and it doesn't show my commit message or the default either tbh
```
➜ git commit --dry-run
Alias tip: g commit --dry-run
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   .config/nvim/queries/lua/injections.scm
```
when I run just `git commit` with no message though that show my custom commit message

**Comment by TimUntersberger** [comment]
@akinsho does the latest version work for you?

**Comment by akinsho** [comment]
@TimUntersberger yep that works great now 👍🏿
