### ISSUE TITLE
Use vim.notify to display messages

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#193]
At the moment, a library built into the plugin is used for notifications.

I suggesting to use `vim.notify` instead. This will allow users to display messages as they want. For example, using [a dedicated plugin](https://github.com/rcarriga/nvim-notify). Also, this change will simplify the code a lot by delegating all notification stuff to user.

Other plugins use the same approach. [gitsigns](https://github.com/lewis6991/gitsigns.nvim/commit/4f0bf0d931da1d2b55f64a87a9fe11e39681194d), for example.

Let me know if you like the suggestion, I can send a PR for it.

**Comment by TimUntersberger** [comment]
If you could also show me what it would look like together with the plugin you mentioned, I would be down to help you complete the PR. Open a draft PR once you start working on this so we can discuss the refactor as early as possible.

**Comment by Shatur** [comment]
Okay!
Should be simple. I'll replace all notification calls with `vim.notify` and all messages will be displayed in echo area by default. Then users can simply override `vim.notify` with any function, like with `require("notify")` from [nvim-notify](https://github.com/rcarriga/nvim-notify) to have nice and consistent popups :)

**Comment by Shatur** [comment]
@TimUntersberger opened #194.
