### ISSUE TITLE
Diffview works only once

### ISSUE THREAD

**Issue by timsofteng** [TimUntersberger/neogit#195]
Hello. Diffview works only once. Then I press `q` to go back to `neogit` and try to open diff for another file and see nothing.

**Comment by TimUntersberger** [comment]
I cannot reproduce this.

**Comment by timsofteng** [comment]
> I cannot reproduce this.
> 
> Actions:
> 
> * Press `d` over changed file in unstaged changes
> * Press `q` inside diff view
> * Move cursor to different file
> * Press `d` over changed file in unstaged changes

Hm
Works now.
Looks like something was changed in neogit or diffview.
I close it.
thanks.
