### ISSUE TITLE
Refresh not work in repo with no commits

### ISSUE THREAD

**Issue by spindensity** [TimUntersberger/neogit#198]
# Steps to reproduce

1. Create a repo with no commits:

```bash
mkdir new_repo
cd new_repo
touch README.md
git init
```

2. Open `README.md` with `neovim`:

```bash
cd new_repo
nvim README.md
```
 
3. Execute `:Neogit` and press <kbd>s</kbd> to stage the `README.md` file.

# Expected behavior

Auto refresh would work in the `Neogitstatus` window, or at least pressing <kbd>Ctrl</kbd> + <kbd>r</kbd> to refresh manually would work.

# Actual behavior

Neither auto refresh nor manual refresh works.

**Comment by TimUntersberger** [comment]
@spindensity is this fixed for you?

**Comment by spindensity** [comment]
> @spindensity is this fixed for you?

Yes, it works now, thanks!
