### ISSUE TITLE
[Bug] Openig commit popup is not working

### ISSUE THREAD

**Issue by dhananjaylatkar** [TimUntersberger/neogit#202]
Looks like recent change has broken commit popup.

Error - 
<img width="1435" alt="Screenshot 2021-09-02 at 11 39 30 PM" src="https://user-images.githubusercontent.com/27724944/131895268-894ac131-17d9-4e86-8881-bd38b1383cf0.png">

**Comment by TimUntersberger** [comment]
Can you try the latest version?

**Comment by dhananjaylatkar** [comment]
It's working! Thanks for super fast response.
