### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by gegoune** [TimUntersberger/neogit#203]
Hi, a while ago I have noticed that sourcing `~/.local/share/nvim/site/pack/packer/start/neogit/plugin/neogit.vim` takes about 30ms during mvim's startup. With impatient.nvim this is cut down to 10-12ms which still makes neogit one of slowest plugins to load. I am wondering what is happening at startup that takes so long. Cannot it be deferred to when neogit's tab page is actually opened?

Thanks for great plugin once again, using it every single day!

**Comment by TimUntersberger** [comment]
How are you measuring the startup time?

**Comment by gegoune** [comment]
With `--startuptime <file>` argument.

**Comment by TimUntersberger** [comment]
I managed to reduce the startuptime from 37ms to 2ms

**Comment by TimUntersberger** [comment]
This might also fix #46.
