### ISSUE TITLE
Default commit's switches and/or options

### ISSUE THREAD

**Issue by soywod** [TimUntersberger/neogit#205]
I always use the `-S` argument (or `--gpg-sign`) when I commit. I would love to have this option activated by default for all my commits. Is there a way to do so? If not then I'm ready to help and propose a PR.

**Comment by RianFuro** [comment]
This is tracked as #80, feel free to help out :) 
I'm closing this one as duplicate

**Comment by soywod** [comment]
I also noticed 3 things:

- Neogit `-S` is a bit confusing. The git man states that `-S` is an alias for `--gpg-sign`, which enables gpg. Magit uses `-S` to enable gpg. But neogit uses `-S` to *disable* gpg. In my opinion, neogit should align with git and magit. Also, having a switch for disabling gpg does not make sense, since it is the default behaviour (magit does not have such switch BTW).
- `git commit -S` can be used without keyid (in this case, the default one is picked), it could be interesting to have such feature.
- magit does not propose this default keyid, but instead autocomplete with existing keys. This is sth that could definitely be useful.

I just saw your reply while typing mine (what a timing!), sorry not to have seen the issue (I looked for a similar one before opening this one).

Tell me your opinion about those points, I can also propose PRs if it sth you are interested in!

**Comment by soywod** [comment]
> I always use the `-S` argument (or `--gpg-sign`) when I commit. I would love to have this option activated by default for all my commits. Is there a way to do so? If not then I'm ready to help and propose a PR.

In fact, this can be done via the git config:

```ini
# $HOME/.gitconfig

[commit]
  gpgSign = true
```

**Comment by RianFuro** [comment]
> Also, having a switch for disabling gpg does not make sense, since it is the default behaviour (magit does not have such switch BTW).

This switch makes sense if you have the gpgSign enabled in your git config (like you just found :D). I have the same configuration and use that from time to time, when I don't have my yubikey handy.

> In my opinion, neogit should align with git and magit.

I'm totally with you on aligning that.
That being said, magit doesn't have a switch for disabling gpg signing - I needed one, so I just put it there. Similarly, since nobody asked for a signing switch yet, there is none. 
We're totally open for ideas how to design that better - I want to keep the option to disable gpg signing though, in some shape or form :sweat_smile:

**Comment by soywod** [comment]
> This switch makes sense if you have the gpgSign enabled in your git config (like you just found :D). I have the same configuration and use that from time to time, when I don't have my yubikey handy.
> 

Indeed, it makes sense in this case! I understand better.

> I want to keep the option to disable gpg signing though

I would still change the default mapping `-S` which is really confusing, what do you think?

For the other points, I will try to propose a PR so we can discuss on.

**Comment by RianFuro** [comment]
> I would still change the default mapping -S which is really confusing, what do you think?

Totally on board with that. Since git has a bunch of those options where only the positive case has a shortcut, maybe a convention like `-!S` for `--no-gpg-sign` would make sense to map the negative cases in neogit? Just an idea though

**Comment by soywod** [comment]
I'm afraid `-!S` will loose even more people xD after all, do you need a _shortcut_? I mean, `--no-gpg-sign` is long but it's not sth you will use everyday (maybe you personally but not people in general).

**Comment by soywod** [comment]
Plus you don't need to type it, since you can just select it with `<tab>`, so I don't see any problem of having only a long form of the switch.

**Comment by TimUntersberger** [comment]
> I'm afraid -!S will loose even more people 🤣 after all, do you need a shortcut?

How would having a shortcut for something loose people? Can you elaborate?

**Comment by soywod** [comment]
I mean, the form of `-!S` could loose people (the `!` is really not common in CLI switches).
