### ISSUE TITLE
Problems signing commits with gpg --pinentry-mode loopback

### ISSUE THREAD

**Issue by yngwi** [TimUntersberger/neogit#210]
Hi,

I'm trying to replace vim-fugitive with Neogit as I like its general user interface but I'm having problem signing my commits. I have set gpg to use `--pinentry-mode loopback` due to the fact that I often work in various environments where the popups don't work but in Neogit I don't get the possibility to enter my key secret. With vim-fugitive I get the possibility to enter the key in the command line but with Neogit nothing happens exept a small "commiting" popup:
![image](https://user-images.githubusercontent.com/963440/132485616-1ab4ce2c-d3c0-4315-8540-011170ea7ad4.png)

Any help is appreciated.
Daniel

**Comment by TimUntersberger** [comment]
Can you show me a small video where you show me what it looks like in the normal git cli?

**Comment by yngwi** [comment]
> 
> 
> Can you show me a small video where you show me what it looks like in the normal git cli?

Do you mean outside of nvim just on the terminal?

**Comment by TimUntersberger** [comment]
> Do you mean outside of nvim just on the terminal?

yeah please 👍

**Comment by yngwi** [comment]
https://giphy.com/gifs/MyZGtajRktljESTB7D

**Comment by TimUntersberger** [comment]
Should be fixed in the latest version.

**Comment by yngwi** [comment]
It works, thank you!
