### ISSUE TITLE
Open in current window/buffer.

### ISSUE THREAD

**Issue by pard68** [TimUntersberger/neogit#230]
**Is your feature request related to a problem? Please describe.**
Neogit always opens in a new window/split or in a new tab.

**Describe the solution you'd like**
It would be nice if there was an option to open Neogit in the _current_ window, respecting my existing splits. I believe this is the default behavior of `magit` or at least it's how it's setup in Doom Emacs.

**Comment by kuntau** [comment]
You can open it in split with `:Neogit kind=split` can be `split_above/vsplit/floating/tab` too

**Comment by cheeze2000** [comment]
No, I'm pretty sure OP is asking for another option to replace the current buffer with Neogit. All the existing options will split the current buffer or window but not replace it.
