### ISSUE TITLE
Splitting hunks further

### ISSUE THREAD

**Issue by augustebaum** [TimUntersberger/neogit#245]
It would be great to be able to split hunks further, the way we're able to in patch mode. To me, neogit is mostly useful to easily pick and choose hunks, so this feature is a no-brainer (though probably not to implement I assume). Unless I just missed it?

It's a killer plugin btw.

**Comment by gegoune** [comment]
What I do when I want to stage/unstage smaller hunk is simply select range I am interested in line-wise and press `s`/`u`.

**Comment by augustebaum** [comment]
Ah neat! I hadn’t realized this was a thing. Perhaps making this clearer in the docs would be useful.

**Comment by avegancafe** [comment]
This might be stupid, but where do you actually select a range? In the file itself? Or in the neogit status

**Comment by CKolkey** [comment]
Use visual-line mode in the status buffer, then stage/unstage to target just the selection

**Comment by avegancafe** [comment]
Oh that is very cool, I didn't realize you could open the diff to a file by hitting tab over the file. Thank you @CKolkey !

**Comment by acampove** [comment]
OH MY GOD, I cannot believe you can do that. You definitely need to document this better somewhere @CKolkey

**Comment by CKolkey** [comment]
> OH MY GOD, I cannot believe you can do that. You definitely need to document this better somewhere @CKolkey 

Documentation is not my strong suit 😅
