### ISSUE TITLE
Git colors / terminal escape codes

### ISSUE THREAD

**Issue by dycw** [TimUntersberger/neogit#247]
### Description

Thanks for the great plugin!

`neogit` doesn't seem to be parsing my git diff colors correctly.

### Neovim version

```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f/build/config -I/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f/src -I/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f/build/src/nvim/auto -I/build/neovim-ahAEvG/neovim-0.6.0~ubuntu1+git202111081211-8cbe100fc-adeb5640f/build/include
Compiled by buildd@lcy01-amd64-014

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 20.04

### Steps to reproduce

My current setup is `LunarVim` with [this](https://github.com/dycw/dotfiles/blob/0.13.1/lvim/config.lua) config file.

### Actual behavior

On the left is the `git commit` dialogue for `neogit`, and on the right is `fugitive`:

![Screenshot from 2021-11-09 04-30-04](https://user-images.githubusercontent.com/10572122/140813666-6850bc87-0eac-45f1-ab18-722380bbe484.png)

### Minimal config

```Lua
My current setup is `LunarVim` with [this](https://github.com/dycw/dotfiles/blob/0.13.1/lvim/config.lua) config file.
```

**Comment by TimUntersberger** [comment]
The point of the minimal config is that we know a different plugin doesn't actually cause this problem. Can you try with our minimal config again?

**Comment by sindrets** [comment]
@dycw This is almost certainly related to your git config. You probably have `color.ui=always` or something similar. This forces git to produce output with colors embedded as ANSI escape sequences in all output. You should be using `color.ui=auto` unless you have a specific reason to enforce the use of ANSI colors regardless of context. You can check your current color settings with:

`git config --get-regexp '^color.*'`

@TimUntersberger We might want to account for this by just always prepending `-c 'color.ui=never'` to all commands executed from `cli.lua`.

**Comment by dycw** [comment]
@TimUntersberger sorry about this, I'll get to go and strip this down next time I get a moment. 

But if it's git config related, I'll try that first and report back.

**Comment by TimUntersberger** [comment]
> @TimUntersberger We might want to account for this by just always prepending -c 'color.ui=never' to all commands executed from cli.lua.

I guess this makes sense 👍

**Comment by dycw** [comment]
Hi, just confirmed that this is indeed the case. I shouldn't have set `gitconfig`. Thanks for debugging this for me.

Love the great plugin!
