### ISSUE TITLE
error when running log commands

### ISSUE THREAD

**Issue by molleweide** [TimUntersberger/neogit#265]
### Description

error when pressing the commands for logging from within the log-pane.
I get the error below when trying to:
log from neogit pane w/`L`
log from neogit pane w/`b`
log from neogit pane w/`a`

`l` log for current branch work as it should.

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

### Operating system and version

macos 11.5

### Steps to reproduce

todo..

### Actual behavior

``` vim
E5108: Error executing lua ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...nvim/site/pack/p
acker/opt/neogit/lua/neogit/lib/util.lua:124: attempt to get length of local 'str' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:113: in function 'callback'
        ...vim/site/pack/packer/opt/neogit/lua/neogit/lib/popup.lua:214: in function 'cb'
        ...im/site/pack/packer/opt/neogit/lua/neogit/lib/buffer.lua:298: in function <...im/site/pack/packer/opt/neogit/lua/neogit/lib/buffer.lua:297>

        ...ck/packer/opt/neogit/lua/neogit/lib/mappings_manager.lua:9: in function 'invoke'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

### Minimal config

I shall do this and report back.

**Comment by TimUntersberger** [comment]
Duplicate https://github.com/TimUntersberger/neogit/issues/258

**Comment by molleweide** [comment]
I'm sorry, my bad I should have researched issues better.
