### ISSUE TITLE
NEOGIT_COMMIT_EDITMSG Can't open file for writing: no such file or directory   

### ISSUE THREAD

**Issue by DPDmancul** [TimUntersberger/neogit#270]
### Description

When saving the commit message, the following error occurs:
```
<b:66/5c/54^[\^[]4;21;rgb:3c/38/36^[\^[]10;rgb:50/49/45^[\^[]11;rgb:fb/f1/c7^[\^[]12;7^[\.git/NEOGIT_COMMIT_EDITMSG"  
E212: Can't open file for writing: no such file or directory   
``` 

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Manjaro 21.2.1 Qonos Linux 5.10.89-1-MANJARO

### Steps to reproduce

1. cd into a git repository
2. `nvim -nu minimal.lua`
3.  `:Neogit`
4. Optionally stage some files
5. Do a commit (`cc`)
6. Write a commit message
7. Save commit message (`:w` or `ZZ`)

### Expected behavior

Create a commit with provided commit message

### Actual behavior

Error
```
<b:66/5c/54^[\^[]4;21;rgb:3c/38/36^[\^[]10;rgb:50/49/45^[\^[]11;rgb:fb/f1/c7^[\^[]12;7^[\.git/NEOGIT_COMMIT_EDITMSG"  
E212: Can't open file for writing: no such file or directory   
``` 
No commit created

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by kuntau** [comment]
Got some related error

```
128 git commit --file=.git/NEOGIT_COMMIT_EDITMSG  --  (3.213 ms) [stderr 1]
  | fatal: could not read log file '.git/NEOGIT_COMMIT_EDITMSG': No such file or directory
```

Now, I can't commit anymore

**Comment by stephenhillier** [comment]
@DPDmancul I had a similar error, and the issue (for me) was something in my `.bashrc` that outputted some ASCII art when I opened a shell. This was the source of the extra characters pre-prended to `.git/NEOGIT_COMMIT_EDITMSG`.

I found the problem using this command:

```
:lua print(vim.trim(vim.fn.system("git rev-parse --git-dir")))
```

**Comment by DPDmancul** [comment]
Thank you very much.
I use fish and moving the welcome message (fish_greeting) into the interactive part of the config solved the problem.
