### ISSUE TITLE
Add autoclose option.

### ISSUE THREAD

**Issue by zbindenren** [TimUntersberger/neogit#275]
**Is your feature request related to a problem? Please describe.**
I often stage, commit and then push changes. Then I have to close the the neogit view.

**Describe the solution you'd like**
Would be cool that after push is finished and succeded, neogit closes automatically.

Or we could have something like:

```
autoclose_on: commit|push|pull
```

**Describe alternatives you've considered**
Close manually :-)

**Additional context**
I know this is only for lazy people like me.

**Comment by gegoune** [comment]
Or maybe introduce events which users could subscribe to, would cover that case and, I assume, many others without being too specific about implementation on neogit side.

**Comment by TimUntersberger** [comment]
I'd say just using vim user autocommands like we did for the refresh event should be fine.
