### ISSUE TITLE
Neogit shouldn't show interactive list of branches for "checkout new branch"

### ISSUE THREAD

**Issue by abusch** [TimUntersberger/neogit#309]
### Description

It looks like a recent commit ( #307 ) added an interactive branch list to some commands in Neogit. It's neat, but I don't think "checkout new branch" (`b c`) should display it. Since we're creating a new branch, we don't need to show the existing one (and it took me a while to figure out that I could press `Enter` to show the prompt).

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

### Operating system and version

macOS 12.4

### Steps to reproduce

1. Open Neogit
2. Type `b c`

### Expected behavior

Being prompted for a name for the new branch.

### Actual behavior

List of existing branches is shown.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by abusch** [comment]
Oh, I see! Thanks for the clarification.

I think displaying some text to explain what the branch list is for would be a useful addition, as well as making the list filterable so I can just type "main" instead of navigating to it. In any case, that's probably a different issue, so I'm happy to close this one.

Out of curiosity, would it be possible to use neovim's `ui.select` instead of a custom buffer?

**Comment by kessejones** [comment]
I think it would be possible, but I don't know if it would be a good idea since other plugins can override its implementation.
