### ISSUE TITLE
Including luaunit?

### ISSUE THREAD

**Issue by RianFuro** [TimUntersberger/neogit#32]
Should we include [luaunit](https://github.com/bluebird75/luaunit) to be able to run some unit tests? Judging from our discussions from #30 we could really benefit from some :)

**Comment by TimUntersberger** [comment]
Sure why not

**Comment by RianFuro** [comment]
Took some time to look at the options. 

As far as pure lua goes, setting up `luaunit` is super straightforward and it's also only a single file. I can even include basic util functions from the `vim` object by just pointing the lua_path over to my nvim installation, but anything touching viml or buffers is off-limits of course.

[busted](https://olivinelabs.com/busted/) also exists but likes luarocks, so I'm not considering that.

[gitsigns](https://github.com/lewis6991/gitsigns.nvim) has a very interesting approach:
https://github.com/lewis6991/gitsigns.nvim/blob/main/Makefile
They basically pull neovim source and run it's unit test setup, but pointing it over to their own tests.

Finally, [plenary](https://github.com/nvim-lua/plenary.nvim) has gotten a pretty usable testing setup recently and can run on a headless neovim instance. Also seems to get actively worked on.

Any preferences? Otherwise I'd go with plenary, since it seems to give the most bang for the least setup

**Comment by TimUntersberger** [comment]
👍 for plenary.
