### ISSUE TITLE
Pre Commit Hooks

### ISSUE THREAD

**Issue by cwittlinger** [TimUntersberger/neogit#329]
### Description

When using neogit to commit something in a repository that uses pre-commit hooks, those hooks are not executed. It rather just skips those hooks and commit immediately.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Linux version 5.15.57-2-MANJARO

### Steps to reproduce

1. `nvim .`
2. Open neogit
3. `cc`
4. No pre-commit hooks executed

### Expected behavior

Pre commit hooks are executed.

### Actual behavior

Pre commit hooks are not executed

### Minimal config

```Lua
...
```

**Comment by gegoune** [comment]
Not much to add except that pre-commit does run for me when committing through neogit.

**Comment by cwittlinger** [comment]
Okay - just figured it out - It runs after the commit message opposed to before (sorry about this)

**Comment by weilbith** [comment]
How can I see the output of the running hooks? Especially for long running hooks it is bit annoying to see nothing and just wait, starring to the notification section.

**Comment by atomdmac** [comment]
@weilbith I know you can do `$` to see a history of _git commands_ but I would also really like to be able to see the actual output from a hook so I can troubleshoot.

**Comment by DMunkei** [comment]
Can someone confirm that this is still the case? I'm using `neogit` on the `master` branch and have it up to date. When I commit something and then press `$` to check the commands issued, there's nothing regarding `pre-commit` or whatsoever.

I'm not entirely sure that it's being run.

**Comment by CKolkey** [comment]
commit hooks are not shown in the command output (`$`), but _do_ get shown in a buffer as they are running. There's an `auto_close_console` config boolean that can be set to prevent closing it in the case of a success, but it should persist in the event of a non-zero exit status.


Here's what you should see:
https://github.com/user-attachments/assets/1a4e2635-1e85-499c-a796-22a15ed6368d
