### ISSUE TITLE
Provide Visual Feedback if Operation is In Progress

### ISSUE THREAD

**Issue by atomdmac** [TimUntersberger/neogit#339]
**Is your feature request related to a problem? Please describe.**
I work with a few repos that have fairly long-running pre-commit hooks.  I love that Neogit doesn't block Neovim while that operation is running but I wish I was able to see the output of the long-running command (or at least some visual indication that there is an operation in progress).

**Describe the solution you'd like**
Ideally, output from the Git command would be piped to a new temporary buffer so it can be observed while the command runs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aleprovencio** [comment]
That is right @atomdmac, and would like to add that I was having a great experience with `neogit` until I had to deal with a `pre-commit` enabled repos, which then turned into something far from bearable.

I've also seen #329, if you all agree we can make another issue focusing only on `pre-commit` integration.

**Comment by coldis** [comment]
In lazygit, the pre-commit hook is run before giving the user the opportunity to enter the commit message. Personally I liked this flow as there was no risk of writing a commit message that was lost because the commit failed.

**Comment by ten3roberts** [comment]
There are a few ways to handle the precommit hook.

Depending on the needs, a statusline module could show a simple spinner, or a terminal buffer could be opened which shows the running process.

**Comment by aleprovencio** [comment]
I guess the crux is really integrating into `neogit`'s workflow, just like you're doing for rebasing on https://github.com/TimUntersberger/neogit/pull/346

As for the interface, I think of it as a secondary issue and would like anything that just don't break the workflow inside neogit.

I've seen this [plugin](https://github.com/Ttibsi/pre-commit.nvim), but IMO it still misses a lot of polish.

**Comment by ten3roberts** [comment]
I've experimented with a terminal buffer which opens if a command takes more than 1 seconds to run, such as a commit hook running, so the user can se the output.

This buffer also applies to other commands which may be slow

**Comment by aleprovencio** [comment]
I was not able to issue a `:Neogit` command using your repo, any hints?

**Comment by ten3roberts** [comment]
Unfortunately no, the branch is a bit work in progress, so not everything is working.

I will continue and polish the rough edges these following days
