### ISSUE TITLE
Has the amend action stopped working?

### ISSUE THREAD

**Issue by aleprovencio** [TimUntersberger/neogit#345]
### Description

This used to work fine but has stopped some time ago.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Archlinux

### Steps to reproduce

1. make changes on a file
2. use `Neogit` to stage and commit (Profit!)
3. make more changes to the file
4. use `Neogit` to stage and commit with the `--amend` switch turned on (`ca` keymap)
5. Fail :/

### Actual behavior

`Neogit` fails silently and commit is not done

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
What happens if you refresh `C-r` the status buffer.

The PR #346 will improve the amend action slightly, and will make it show an error and refresh if it didn't succeed

**Comment by ten3roberts** [comment]
No, neither before nor after my local changes.

Us there anything in the git log `$`.

What does the commandline say if you do `git commit --amend`

**Comment by aleprovencio** [comment]
> No, neither before nor after my local changes.
 
:/
> Us there anything in the git log `$`.
Nothing on the logs
 
> What does the commandline say if you do `git commit --amend`
It does commit as usual, it's my only hope ! :)

**Comment by aleprovencio** [comment]
I have also noticed that if somehow some commit fails because of an error, after correcting it and commiting again `neogit` will present this same faulty behavior when i try to amend commits.

Maybe it is failing on both cases because it had already saved a commit message?

**Comment by aleprovencio** [comment]
As you said, this https://github.com/TimUntersberger/neogit/pull/346 really improved things ans this is not an issue anymore!

Thank you
