### ISSUE TITLE
Unable to use Neogit after update

### ISSUE THREAD

**Issue by Icy-Thought** [TimUntersberger/neogit#347]
### Description

Re-installed neovim yesterday and after installing all the plugins required for my setup I had noticed that neogit was not operational as it once had been. 

That is to say, it would not work with neither the default configurations (`require("neogit").setup()`) nor with my customized neogit setup.

### Neovim version

NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld (nix overlay: neovim-nightly)

### Operating system and version

NixOS (`nixos-unstable`)

### Steps to reproduce

1. Launch Neovim.
2. Call neogit through usual commands.
3. Greeted with error.

### Expected behavior

A working neogit setup.

### Actual behavior

```
Error executing luv callback:
.../nvim/site/pack/packer/opt/neogit/lua/neogit/process.lua:57: ENOENT: no such file or directory
stack traceback:
        [C]: in function 'error'
        .../nvim/site/pack/packer/opt/neogit/lua/neogit/process.lua:57: in function 'returned_functi
on'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:31: in function 'callback_or_nex
t'
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:45: in function 'cb'
        .../nvim/site/pack/packer/opt/neogit/lua/neogit/process.lua:16: in function 'raise_if_fully_
closed'
        .../nvim/site/pack/packer/opt/neogit/lua/neogit/process.lua:50: in function <.../nvim/site/p
ack/packer/opt/neogit/lua/neogit/process.lua:44>
```

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by xanderio** [comment]
I did a quick bisect and the first "bad" commit is 9c63259c56e13e3385705fd44722f31381045c0c, this commit was part of #346 by @ten3roberts .

Not sure if this is limited to NixOS, as I can test this on a another OS currently.

**Comment by ten3roberts** [comment]
If you place a print of the command and args above https://github.com/TimUntersberger/neogit/blob/463820a83f4ba387655f370a17c87dc3100cdf0d/lua/neogit/process.lua#L44, what does it say.

My hunch is that is failes to execute the binary because they are in a different place on nixos

**Comment by ten3roberts** [comment]
Did rebase interactive work for you before my PR, because they use the same mechanism.

If rebase interactive didn't work for you before then the problem is likely deeper

**Comment by Icy-Thought** [comment]
I tried using rebase interactive from e6d8ec6 and it appears as if rebase interactive does nothing besides entering rebase when saved.

***Side-note***: Nix does store binaries in `/nix/store` and symlinks them to appropriate locations. Therefore this might be the cause of the issue, but that I cannot confirm due to being unaware of how the appropriate binaries are being called in neogit.

**Comment by ten3roberts** [comment]
What happens if you go into neogit inside the packer dir, and uncomment this line?

https://github.com/TimUntersberger/neogit/blob/463820a83f4ba387655f370a17c87dc3100cdf0d/lua/neogit/process.lua#L52

It will show which command is attempting to run. As you said, they should be in the path, unless an explicit `/usr/bin/git` is being used somewhere

**Comment by xanderio** [comment]
```
started process {                                                                                                                   
  args = { "--no-optional-locks", "ls-files", "--others", "--cached", "--modified", "--deleted", "--full-name", "src/cli.rs" },
  env = { "HOME=/home/xanderio", "GNUPGHOME=/home/xanderio/.gnupg", "NVIM=/run/user/1000/nvim.2233242.0" },
  stdio = { <userdata 1>, <userdata 2>, <userdata 3> }
} -> nil ENOENT: no such file or directory @@ nil
```

**Comment by xanderio** [comment]
I found the issue and the fix, as mention in the comment on line 32, the enviroment is completely overridden this causes problems as the `$PATH` the child gets is missing all the NixOS PATH magic.

The fix is really simple just add `table.insert(params.env, string.format("%s=%s", "PATH", os.getenv("PATH")))`.

**Comment by xanderio** [comment]
I have just discovered that commit singing via ssh is also effected by this as the SSH agent related variables are unavailable to the child.
