### ISSUE TITLE
Environment issues when committing

### ISSUE THREAD

**Issue by itmecho** [TimUntersberger/neogit#356]
### Description

When I commit, I get issues where my pre-commit hook fails to run because it can't find the a required binary. The binary is in my PATH and if I run `lua print(vim.inspect(vim.fn.executable('pnpm')))` then it returns `1` as expected.

I think this is a problem with the environment rather than my pre-commit hook as it was working until I ran `PackerSync` a few days ago.

Also, if I use the `--no-verify` flag, it continues as expected but then when I try to write and quit the commit message, I get another error because it failed to GPG sign the commit. This is because the git command can't access the gpg socket environment variable.

### Neovim version

```
NVIM v0.8.0-dev-1173-gc815aadfc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/iain/src/neovim/build/cmake.config -I/home/iain/src/neovim/src -I/home/iain/src/neovim/.deps/usr/include -I/usr/include -I/home/iain/src/neovim/build/src/nvim/auto -I/home/iain/src/neovim/build/include
Compiled by iain@orion

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/iain/.local/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

```
Void Linux 5.18.19_1 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 14:36:55 UTC 2022 x86_64 GNU/Linux
```

### Steps to reproduce

1. Add a basic script somewhere in your PATH. For me that's `~/.local/bin`.
```sh
echo 'echo hi' > ~/.local/bin/neogit-test
chmod 755 ~/.local/bin/neogit-test
```
2. Test that you can run that command from your shell
```sh
$ neogit-test
hi
```
3. Init a git repo
```sh
cd /tmp
mkdir neogit-repro
cd neogit-repro
git init
```
4. Add pre-commit hook
```sh
cat <<EOF > .git/hooks/pre-commit
#!/bin/sh

neogit-test
EOF
chmod 755 .git/hooks/pre-commit
```
5. Test it works in your shell. You should see `hi` printed out in the output of the commit command.
```sh
touch file1
git add file1
git commit -m "commit 1"
```
6. Do the same process from step 5 using neogit: `nvim -nu minimal.lua`
```vim
e file2
w file2
Neogit
# Then `cc` in the neogit window to commit 
```

This is the point I get the error

### Expected behavior

Successful commit

### Actual behavior

I get this popup:
![image](https://user-images.githubusercontent.com/8384983/193018125-8a9207e4-edd4-4137-913e-af2167b42613.png)

and I get this in the log (`$`)
```
  1 git --no-optional-locks commit (0.001 ms) [stderr 1]
  | .git/hooks/pre-commit: 3: neogit-test: not found
```

This definitely wasn't happening before. I'm not exactly sure which commit changed it though.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by gegoune** [comment]
Probably related to #351

**Comment by itmecho** [comment]
Ah yes, confirmed that it's working again on the master branch :raised_hands:
