### ISSUE TITLE
Precommit failure is not surfaced to the user

### ISSUE THREAD

**Issue by jared-smith-kr** [TimUntersberger/neogit#373]
### Description

Related to [#329](https://github.com/TimUntersberger/neogit/issues/329) and [#339](https://github.com/TimUntersberger/neogit/issues/339).

When a precommit hook fails (and therefor the commit is aborted) that information is not surfaced to the user: there is no indication that the commit failed other than the fact that the changes are still in staged in the interface.

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS Monterey

### Steps to reproduce

1. Have a git precommit hook that fails (e.g. the staged files fail lint/style check)
2. Move file to staged
3. Commit
4. Watch the committing... toast fade away with no other visual indication.

### Expected behavior

Error message from STDERR surfaced to the user.

### Actual behavior

Nothin

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
Would this be fixed with the recent merges?

There should now be a colored log buffer which pops up if a commit hook failed

**Comment by jared-smith-kr** [comment]
I ran PackerSync and it's fixed now, although there seems to be a bit of inconsistency if files get altered as a result of the hook (e.g. formatter --write). Good enough for this issue though, thanks!
