### ISSUE TITLE
:Neogit command is missing

### ISSUE THREAD

**Issue by abusch** [TimUntersberger/neogit#379]
### Description

I recently updated neogit and the `:Neogit` command is gone. Opening neogit using the lua api still works though (i.e `:lua require('neogit').open()`).

It seems to be caused by [this change](https://github.com/TimUntersberger/neogit/pull/358/commits/0ae9fc91b102b3c2f70de767b7003b8b8038dee3#diff-55b344b98ef0e2242a2dd20a8888e3b01e696c8b9707fcacff6a49d9075fc46a) from PR #358 where the whole `plugin/neogit.vim` file, which defined the command, got removed. I suspect the file got rewritten in Lua, but the part that defined the command at the bottom got missed.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system and version

macOS 12.6

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. type `:Neogit`

### Expected behavior

I expect `:Neogit` to start neogit

### Actual behavior

`:Neogit` command is not defined.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by dpetka2001** [comment]
Unfortunately I get an error in latest nvim-nightly and Neogit interface doesn't open at all with the following error: ```
E5108: Error executing lua: ...23/.config/nvim/plugged/neogit/lua/neogit/lib/buffer.lua:137: Expected 1 argument                       
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...23/.config/nvim/plugged/neogit/lua/neogit/lib/buffer.lua:137: in function 'show'
        ...23/.config/nvim/plugged/neogit/lua/neogit/lib/buffer.lua:308: in function 'create'
        .../jrn23/.config/nvim/plugged/neogit/lua/neogit/status.lua:955: in function 'create'
        /home/jrn23/.config/nvim/plugged/neogit/lua/neogit.lua:32: in function </home/jrn23/.config/nvim/plugged/neogit/lua/neogit.lua:2
0>
```
I have in the setup function `kind=replace` and when i comment out this option then Neogit opens normally.

**Comment by caarlos0** [comment]
I'm also getting some weird formatting issues:
<img width="575" alt="CleanShot 2022-10-26 at 00 55 59@2x" src="https://user-images.githubusercontent.com/245435/197931049-6df85a9d-ed0e-48cb-9db5-57a80c490a02.png">

the `^D^H^H` to be precise... not sure if it is related, but I noticed the 2 issues after the same upgrade...

**Comment by ten3roberts** [comment]
That looks like some color codes made it through to the git-log parsing.

What does `git --no-pager -c color.ui=always status --porcelain=2 --branch` and `git --no-pager -c color.ui=always log --oneline "@{upstream}.."

Also, does it always happen or is it occasionally, andwhich OS?

**Comment by abusch** [comment]
For me, it happens consistently, and I'm on macOS. The 2 commands don't seem to show anything suspicious when I run them:
<img width="1102" alt="Screenshot 2022-10-26 at 21 05 18" src="https://user-images.githubusercontent.com/506344/197998529-fa75f8d0-4a97-47d4-a33d-8d858a2ad23e.png">

**Comment by kronikpillow** [comment]
same issues here :-/

**Comment by ten3roberts** [comment]
I have created a branch with one of my theories of the issue, though I have not managed to recreate it myself.

Does checking out https://github.com/ten3roberts/neogit/tree/git-escapes make any difference.

I am glad to help

**Comment by abusch** [comment]
@ten3roberts I just gave your branch a try, and it's looking much better:

<img width="732" alt="Screenshot 2022-10-27 at 08 16 51" src="https://user-images.githubusercontent.com/506344/198140017-2120ba81-64c9-4101-911d-6a74c3662f6b.png">

Thanks for the help!

**Comment by heftyfunseeker** [comment]
> I have created a branch with one of my theories of the issue, though I have not managed to recreate it myself.
> 
> Does checking out https://github.com/ten3roberts/neogit/tree/git-escapes make any difference.
> 
> I am glad to help

This worked for me as well (macOS). Many thanks!

**Comment by EvanCarroll** [comment]
> It seems to be caused by [this change](https://github.com/TimUntersberger/neogit/pull/358/commits/0ae9fc91b102b3c2f70de767b7003b8b8038dee3#diff-55b344b98ef0e2242a2dd20a8888e3b01e696c8b9707fcacff6a49d9075fc46a) from PR https://github.com/TimUntersberger/neogit/pull/358 where the whole plugin/neogit.vim file, which defined the command, got removed. **I suspect the file got rewritten in Lua, but the part that defined the command at the bottom got missed.**

That's good research, and a sound theory. However, if so, is anything on this plugin tested as part of the CI or publication step? Certainly, that of all things should be caught. I see there are tests. None of them test `:Neogit`?

**Comment by dpetka2001** [comment]
Does `require('neogit').open( { kind = "replace" } )` work for anyone? Cuz I get an error mentioned in my previous post when I have this option set. Without this option `kind = "replace"` I can also open Neogit fine from the Lua Api.

**Comment by ten3roberts** [comment]
@EvanCarroll I agree with you. The tests are run during CI, but it doesn't fail if the tests fail, which is not the best.

But yes, it should have been caught.

The replace kind is also fixed by the coming pr
