### ISSUE TITLE
Color codes in git output

### ISSUE THREAD

**Issue by MartyBeGood** [TimUntersberger/neogit#382]
### Description

Follow up of #379 , sort of.

#380 removed the `^D^H^H` prefixes to "everything" on Linux for me (which is awesome)

On macOS, they're not quite gone yet. They've changed from `^D^H^H` to `^D`.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

### Operating system and version

macOS 13

### Steps to reproduce

1. nvim -u minimal.lua in a git repo
2. :Neogit
3. observe `^D` in unpulled, unmerged commits and at the start of the commit message on Head: and Push:

### Expected behavior

No `^D` characters

### Actual behavior

![image](https://user-images.githubusercontent.com/6429294/198241378-49437e9e-8d80-4b4a-91fd-936b592dbfda.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by danilshvalov** [comment]
Hi! Could you test #388, please?
