### ISSUE TITLE
Strange prefix `^D` all over the place

### ISSUE THREAD

**Issue by strash** [TimUntersberger/neogit#384]
### Description

Also appears with minimal config.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 13.0

### Steps to reproduce

I actually don't know how to reproduce it

### Actual behavior

<img width="911" alt="Screenshot 2022-10-27 at 19 22 39" src="https://user-images.githubusercontent.com/14233263/198345522-3a192cd5-4ded-4a04-92b5-9cfee03957eb.png">

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by strash** [comment]
Duplicate of #383

**Comment by snowair** [comment]
![企业微信截图_638b781c-d594-46e8-be7b-387f809058f5](https://user-images.githubusercontent.com/1695133/198579833-ab3c2771-b97f-48eb-8b4e-4e4212a6b087.png)

**Comment by emanuel2718** [comment]
Same behavior with default configuration

### Neovim version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew


![image](https://user-images.githubusercontent.com/55965894/198706742-5b348dcb-03c1-4fdb-beae-faaf95a004c5.png)

**Comment by danilshvalov** [comment]
Hi! Could you test #388, please?

**Comment by strash** [comment]
@danilshvalov, hi! This fixed the problem for me.
Should I close the issue?

**Comment by danilshvalov** [comment]
@strash
I think you shouldn't close the issue until the patch is merged.

**Comment by strash** [comment]
@danilshvalov ok, thank you!
