### ISSUE TITLE
Stash not visible

### ISSUE THREAD

**Issue by tobealive** [TimUntersberger/neogit#394]
### Description

happens since 83526c3d9bfe9e68afdcbede1137968b7d7bac43

### Neovim version

v0.8

### Operating system and version

Linux 5.15

### Steps to reproduce

Open Neogit Status while having git stashes

### Expected behavior

Stash visible in Neogit Status

### Actual behavior

Stash not visible

### Minimal config

```Lua
-
```

**Comment by ten3roberts** [comment]
Can confirm the same behavior here.

The stash is as of now quite broken, but will hopefully soon be fixed

**Comment by ten3roberts** [comment]
This should not we fixed. Can you confirm on your end?

**Comment by tobealive** [comment]
did a quick check and it lgtm.

thank you! @ten3roberts
