### ISSUE TITLE
Neogit leaves empty buffer every time it's open

### ISSUE THREAD

**Issue by Strongleong** [TimUntersberger/neogit#404]
### Description

Every time I open Neogit it creates new empty buffer.

Just opened file "test.txt":
![image](https://user-images.githubusercontent.com/17177071/202617438-5aff9494-7e45-43c6-81f4-9b77d0bdf90c.png)

Opened and closed Neogit:
![image](https://user-images.githubusercontent.com/17177071/202617498-9ea3639c-ec13-4d70-b51e-ae469b3db708.png)

Opened and closed Neogit for the second time:
![image](https://user-images.githubusercontent.com/17177071/202617522-cf1bc57f-0902-4c02-bffd-e73f1a0eb5b0.png)

Bug reproduces with "minimal.lua" config

P.S. Sorry for bad English :sweat_smile: 

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system and version

Arch Linux

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. check `:buffers`
3. open Neogit `:Neogit`
4. check `:buffers` again, note that second buffer appears
5. close Neogit `q`
6. check `:buffers` again, note that second buffer did not disappeared

### Expected behavior

No additional buffers created

### Actual behavior

Empty additional buffers created every time I open Neogit

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by Feel-ix-343** [comment]
Any update on this?

**Comment by Strongleong** [comment]
I checked every kind of Neogit. Only `tab` kind creates and leaves empty buffer

**Comment by Strongleong** [comment]
I think I located the problem. It is in file `lua/neogit/lib/buffer.lua`, line 142. `api.nvim_set_current_buf` do not replaces current buffer, but creates new one. Event is current buffer is empty buffer. Guess it is neovim bug rather than neogit

**Comment by Strongleong** [comment]
Tried replicate with `nvim --clean`. No additional buffer created. Strange...

**Comment by Strongleong** [comment]
Hmm.. Guess I did something wrong while testing.

I tried emulate creating new buffer in new tab like Neogit dose, only by hand:
```vim
nvim -nu minimal.lua test.txt
:tabnew
:lua vim.api.nvim_set_current_buf(vim.api.nvim_create_buf(false, false))
```

And it created second empty buffer (first one created by `:tabnew`. But it didn't reproduced with `nvim --clean`. 
And now I can't reproduce it **by hand** nor with clean neovim, nor with `minial.lua` config.

The actual bug still reproduces

**Comment by kskarthik** [comment]
I also face similar issue

**Comment by mkarbo** [comment]
I have the same issue

**Comment by alistairstead** [comment]
I also have this issue. Any suggested config fix?

**Comment by Strongleong** [comment]
I guess you can hack in some autocmd that will after closing neogit buffer try to find any empty buffers and deletes them. 

P.S. Looks like maintainers don't really care about this issue :(

**Comment by ten3roberts** [comment]
Hi, sorry for the late reply. It should now hopefully be solved.

It was the blank buffer which neovim creates when opening a new tabbage, with a blank buffer, which was just ignored. It should be fixed now.

**Comment by Strongleong** [comment]
Can confirm that issue is fixed. Thank you! ❤️
