### ISSUE TITLE
Impossible to do git rebase interactive on a huge project

### ISSUE THREAD

**Issue by D00mch** [TimUntersberger/neogit#406]
### Description

I press `ri` to start rebase interactive, and it stars scrolling with the speed of light. And I can't find the commit I need with the search `/`.

![imposible_rebase](https://user-images.githubusercontent.com/14236531/203930555-74037eab-fac4-4c8f-940a-1a10b60dd9e4.gif)

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

### Operating system and version

13.0

### Steps to reproduce

Press `ri` on a big project.

### Expected behavior

Just show the last 20 commits, not one million.

### Actual behavior

Crazy scroll for all the history.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
Does https://github.com/TimUntersberger/neogit/tree/limit-rebase-log solve your issue?

**Comment by D00mch** [comment]
Thank you for the reply! 20 is good, but I don't see one of the recent commits
![image](https://user-images.githubusercontent.com/14236531/204318081-76f87cc4-5da4-43c8-ad52-55170dfcdfb2.png)

**Comment by ten3roberts** [comment]
Just to confirm: do the commits in rebase-interactive show up in order? I.e; first 20.

The issue seems to be that recent shows the 20 most recent commits on the checked out branch, but the rebase view shows the 20 most recent commits for all branches

**Comment by D00mch** [comment]
> Just to confirm: do the commits in rebase-interactive show up in order? I.e; first 20.

Yes

> The issue seems to be that recent shows the 20 most recent commits on the checked out branch, but the rebase view shows the 20 most recent commits for all branches

Yes

**Comment by ten3roberts** [comment]
I have copied the code for getting the recent commits and use the exact same for the rebase.

The strange thing is that the `Recent commits` does not explicitly show only the current branch. I think the difference is that since it is using the short it doesn't show merges

**Comment by ten3roberts** [comment]
I have merged some fixes and changes into master, some of which improve rebasing feedback and commit picking.

How is this issue now? Is it possible to find the commit?

**Comment by D00mch** [comment]
Works great! Thank you!
