### ISSUE TITLE
"Error: Cursor position outside buffer" when using the "Go to file" mapping

### ISSUE THREAD

**Issue by lucasmarinb** [TimUntersberger/neogit#410]
### Description

When inspecting the changes in the NeogitStatus buffer i tried to go to a file, lets say `init.lua`, through pressing `Enter` but i got the following error:

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...nvim/site/pack/packer/s
tart/neogit/lua/neogit/status.lua:907: Cursor position outside buffer
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:44>
```

Then it 'sends me' to `init.lua` (at least that's what lualine shows), but it's actually an empty buffer. This error is only happening when editing my neovim config, since i'm working in other javascript projects and i can use the `Go to file` feature without problems.

### Neovim version

NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Pop!_OS 20.04 LTS

### Steps to reproduce

1. Go to the directory where i store my neovim config
2. Run `nvim -nu minimal.lua`
3. Run `:Neogit`
4. Press `Tab` in a file to open the diff view
5. Press `Enter` in the desired line of code of the diff to go to the file

### Expected behavior

I expect to actually go to the file as it was working properly.

### Actual behavior

I open `:Neogit` and open the diffview for a file, in this case `keymaps.lua`:
![image](https://user-images.githubusercontent.com/4324314/206878727-3ec084cb-869d-4f8f-b6c8-0991b282f061.png)

I press `Enter` to go to the file and get the following error:
![image](https://user-images.githubusercontent.com/4324314/206878770-4b72aaa5-5713-4823-9308-9fbade79aa72.png)

Then it "sends me" to the disired file, but it's actually an empty buffer:
![image](https://user-images.githubusercontent.com/4324314/206878823-a9606c31-5066-4d10-8deb-6d12b1c000ec.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by lucasmarinb** [comment]
I did a binary search over the commit history to find a commit before this error was introduced, i discovered that the range where the bug was introduces goes from October 12 to October 25.
* The "last" working commit i found was on [October 12](https://github.com/TimUntersberger/neogit/commit/009ac00e5235349e0e8cead30d1ee032b712486f).
* After that a bug where the **Neogit command was missing** was introduced.
* On October 25, the missing Neogit command was [fixed](https://github.com/TimUntersberger/neogit/commit/092c23b48022d61933020a585ae907c691c2e389). But after this fix my error / **Go to file mapping error** starts happening.

**Comment by vinibispo** [comment]
I was able to reproduce it

**Comment by lucasmarinb** [comment]
> I was able to reproduce it

What did you discover?

**Comment by vinibispo** [comment]
Nothing important. I only discovered that the row and the col are wrong in this part
https://github.com/TimUntersberger/neogit/blob/a0390c51c0e1b4470572858e2adb6690bd6047bb/lua/neogit/status.lua#L926

**Comment by lucasmarinb** [comment]
Well, as of today, it's seems that the problem has been solved.
