### ISSUE TITLE
Neogit fails to run any command and shows error on Windows

### ISSUE THREAD

**Issue by hasansujon786** [TimUntersberger/neogit#424]
### Description

While running some command or opening commit window it shows this error.

      hint: Waiting for your editor to close the file... Error detected while processi

        [string ":lua"]:1: in main chunkCommand running for: 2006.08 ms

64245bb it is the last working commit for me.

### Neovim version

NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az28-353

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

### Operating system and version

Windows 10 Build 19045

### Steps to reproduce

local fn = vim.fn
local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
local is_installed = fn.isdirectory(install_path) == 1
if not is_installed then
  print('Installing packer...')
  fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })
  vim.cmd({ cmd = 'packadd', args = { 'packer.nvim' } })
  print('Installed packer.nvim.')
end

return require('packer').startup({
  function(use)
    use('wbthomason/packer.nvim')
    use('TimUntersberger/neogit')
    use('nvim-lua/plenary.nvim')

    if not is_installed then
      require('packer').sync()
    end
  end,
})

### Expected behavior

Neogit commit window opens without any error on Windows OS

### Actual behavior

Ex: This screenshot was taken while opening commit window.
Without opening NeogitCommitMessage it opens NeogitConsole window and shows this error.
![Screenshot 2023-01-04 222226](https://user-images.githubusercontent.com/38243998/210606537-7fa6da7e-dba4-40e6-90d7-1a5b525ff28e.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by yngwi** [comment]
I have the same or a similar problem: 
![image](https://user-images.githubusercontent.com/963440/212635703-cb169c7b-76a9-4e87-9774-a0a0c9a3b775.png)

**Comment by hasansujon786** [comment]
I believe it is the same problem. @yngwi

**Comment by Strongleong** [comment]
Same issue. Bump.
![изображение](https://user-images.githubusercontent.com/17177071/217193867-fcb70a63-6dcf-48ab-ace8-5e23c16c037a.png)

**Comment by sho-87** [comment]
I'm having the same issue as well

**Comment by ibotha** [comment]
Bump on this, I am getting this issue as well. Willing to wager it is windows specific.

**Comment by hasansujon786** [comment]
@ibotha I think it is windows specific.

**Comment by Strongleong** [comment]
Fixed now

**Comment by Strongleong** [comment]
Np :)
