### ISSUE TITLE
Wrong path when opening file from status

### ISSUE THREAD

**Issue by Quaqqer** [TimUntersberger/neogit#427]
### Description

When opening a file from the `:Neogit` page with `<CR>` the path is wrong if I am not in the root of the git repository. It works fine if I am in the repository root.

I've tried to find any issue like mine, but I can't seem to find one.

If relevant my git version is `2.38.1`.

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/5cnj2vpc2v2xvbxyw3hxwzy4ld3hpmwp-neovim-unwrapped-0.8.1/share/nvim
"

Run :checkhealth for more info

### Operating system and version

NixOS unstable rev e182da8622a354d44c39b3d7a542dc12cd7baa5f

### Steps to reproduce

1. `cd <git_root>/<some_dir>`
2. `nvim -u minimal.lua`
3. `:Neogit`
4. Open a file with `<CR>`

### Expected behavior

When I press `<CR>` when hovering over a file in the status page the correct file is opened.

### Actual behavior

A non-existent file is opened. The relative path is appended to the git-root path. For instance:

If I am in `$GIT_ROOT/dir_a` and open `../file_b` (`$GIT_ROOT/file_b`) the non-existent file `$GIT_ROOT/../file_b` is opened.

Here is an example of my repo `/home/empa/.dots`.

![20230108_13h22m24s_grim](https://user-images.githubusercontent.com/29512047/211196275-9c3ceec0-a6f4-43ab-b741-876eb9c3dc09.png)
![20230108_13h22m40s_grim](https://user-images.githubusercontent.com/29512047/211196284-6835bf97-252a-49a6-a544-5dec74194774.png)

### Minimal config

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
   vim.fn.system({
      'git',
      'clone',
      '--filter=blob:none',
      'https://github.com/folke/lazy.nvim.git',
      '--branch=stable', -- latest stable release
      lazypath,
   })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
   'timuntersberger/neogit',
   dependencies = {
      'nvim-lua/plenary.nvim',
      'sindrets/diffview.nvim',
   },
   config = true,
})
```

**Comment by ten3roberts** [comment]
Does https://github.com/TimUntersberger/neogit/tree/fix-427 solve your issue?

**Comment by duics** [comment]
@ten3roberts Hey, I was having the same issue and can report that the fix is indeed working :+1:
