### ISSUE TITLE
Error message when I open status

### ISSUE THREAD

**Issue by PHSix** [TimUntersberger/neogit#43]
I use command `:lua require'neogit.status.create('floating')'` to create a float buffer to display git message with this message:
![图片](https://user-images.githubusercontent.com/57695072/108691584-a01ef800-7536-11eb-9f01-41f518c50360.png)

**Comment by TimUntersberger** [comment]
Does it work for you when using `'tab'`?

**Comment by PHSix** [comment]
yes, it can work in `tab`.
