### ISSUE TITLE
Cannot commit using neogit with vim-strip-trailing-whitespace installed

### ISSUE THREAD

**Issue by Mange** [TimUntersberger/neogit#436]
### Description

Trying to commit through neogit since the commit 458012d3c6853525d169e5dd9aa153b2ca157d80 no longer works for me, if [vim-strip-trailing-whitespace](https://github.com/axelf4/vim-strip-trailing-whitespace) is installed.

I don't want to presume which "side" here is in error, and I'm not expecting this to be fixed. I want to raise this issue in case someone else is hit by this.

Note that this did not happen before the commit 458012d3c6853525d169e5dd9aa153b2ca157d80. I've cherry-picked the problem to that commit.
Since it started to happen after I updated `neogit`, it felt more natural to me to open the issue here, but I do not place any kind of blame.

I'll remove the other plugin since `neogit` is a lot more important to me. Feel free to close this as a `#wontfix`.

### Neovim version

`LANG=C nvim --version`
```
LANG=C nvim --version
NVIM v0.9.0-dev-721+g2093e574c6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/usr/include/luajit-2.1 -I/usr/include -I/home/mange/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/mange/.cache/paru/clone/neovim-git/src/build/include -I/home/mange/.cache/paru/clone/neovim-git/src/build/cmake.config -I/home/mange/.cache/paru/clone/neovim-git/src/neovim/src
Compiled by mange@socia

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux socia 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux

### Steps to reproduce

1. Prepare empty git repo to test in.
   ```
   mkdir git
   cd git
   git init
   echo foo > test.txt
   git add .
   git commit -m "initial"
   echo bar >> test.txt
   ```
2. Install `minimal.lua`
3. `nvim -nu minimal.lua`
4. `:Neogit`
5. Press <kbd>c</kbd><kbd>c</kbd>.

### Expected behavior

A split is opened with the commit message.

### Actual behavior

A notification is shown. No split is opened. The commit message is opened as a hidden buffer that can only be seen from `:buffers!` (not `:buffers`). Switching to it and trying to write it does not cause a commit.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"TimUntersberger/neogit",
				requires = {
					{ "nvim-lua/plenary.nvim" },
					{ "sindrets/diffview.nvim" },
				},
				config = function()
					print("loaded neogit")
					require("neogit").setup()
				end,
			},
			{
				"axelf4/vim-strip-trailing-whitespace",
			}

		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing neogit and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by nobleach** [comment]
I'm seeing the same behavior. I hadn't narrowed it down to `axelf4/vim-strip-trailing-whitespace` yet so thank you for this!

**Comment by ten3roberts** [comment]
From the looks of if, the plugin attaches to **all** buffers and listens for changes, and for each change does incremental stripping.

This may be the cause of problem as were using `nvim_buf_set_lines` and like commands in the same tick as creating the buffer, and they may be fighting about the buffer content. All this happens before the buffer is shown.

What happens if you comment out this line?

https://github.com/axelf4/vim-strip-trailing-whitespace/blob/59385775cbe416b2797ec5e2c7eb445a3398dd46/plugin/strip_trailing_whitespace.vim#L237

**Comment by nobleach** [comment]
It doesn't resolve the issue. Removing that package altogether does resolve the issue. I may just try not using it for now. Most of the languages I use have their own tooling to "clean up code".

**Comment by Mange** [comment]
Yeah, I suggest you maintainers don't worry about this issue.

I've also gotten rid of the other plugin and will probably not need it anymore, and if I do want something similar I might stick to just a global "remove all trailing whitespace" `autocommand` without all the logic around only stripping touched lines.

If a third person has this problem and want it fixed, they can re-open the issue with a suggested fix. IMHO. :slightly_smiling_face:
