### ISSUE TITLE
Initialize git repository

### ISSUE THREAD

**Issue by ten3roberts** [TimUntersberger/neogit#495]
It would be nice for neogit to be able to initialize a repository if one doesn't exist (or clone, similar to https://magit.vc/manual/2.90.0/magit/Repository-Setup.html).

_Originally posted by @CKolkey in https://github.com/TimUntersberger/neogit/issues/487#issuecomment-1517999648_

**Comment by milkias17** [comment]
I'd really like to work on this. What would be an acceptable pr? How did you imagine getting user input for initializing a repo, I thought we can just prompt a user, would you like to initialize a git repo if they tried to open the neogit window inside a non-git repo. In what form should we take their input, would a simple vim.fn.input suffice?

**Comment by CKolkey** [comment]
Sure! You can use https://magit.vc/manual/magit/Creating-Repository.html as a reference. Essentially you'll be making a function bound to `I` on the status buffer. Heres where thats set up: https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/status.lua#L879

If you follow how emacs magit works, pressing `I` will prompt the user to pick a folder to initialize a repo in. 

Finally, here's a reference for the implementation of such a function: https://github.com/magit/magit/blob/9c66514b2c879a8959b676393467b1f24be71303/lisp/magit-status.el#L205

For now, `vim.fn.input` should be fine.

**Comment by milkias17** [comment]
Ok great thanks a lot for the reply. I'll try my best to achieve this👍

**Comment by CKolkey** [comment]
Sounds good, and feel free to ping me with questions :)
