### ISSUE TITLE
Help popup

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#53]
Having something like the `?` popup in magit for neogit, would be really cool. I keep forgetting about keybindings that I rarely use and then I have to look them up in the documentation. Implementing this popup would simplify these steps and also makes neogit easier to learn.

**Comment by TimUntersberger** [comment]
Implemented in 2f84bde08a4564c95d07ded3eb9dcbb94776d5d3

**Comment by RianFuro** [comment]
That was fast :D quick heads-up though: The stash popup needs the cursor position from the status buffer to be able to work with "the stash entry under the cursor". For that purpose, I've built some kind of *context* to pass to the popup, which only the stash popup uses for now. You'd need to pass that context through the help popup to the stash popup for everything to work.

See:
https://github.com/TimUntersberger/neogit/blob/2f84bde08a4564c95d07ded3eb9dcbb94776d5d3/lua/neogit/status.lua#L784-L786
https://github.com/TimUntersberger/neogit/blob/2f84bde08a4564c95d07ded3eb9dcbb94776d5d3/lua/neogit/popups/stash.lua#L91-L93
https://github.com/TimUntersberger/neogit/blob/2f84bde08a4564c95d07ded3eb9dcbb94776d5d3/lua/neogit/popups/stash.lua#L46-L50
https://github.com/TimUntersberger/neogit/blob/2f84bde08a4564c95d07ded3eb9dcbb94776d5d3/lua/neogit/lib/popup/lib.lua#L197-L218
