### ISSUE TITLE
Add Neogit commands

### ISSUE THREAD

**Issue by clason** [TimUntersberger/neogit#55]
It'd be nice if one could bypass the main Neogit status window by directly entering, say `:Neogit commit` (or `lua neogit.commit()`) to save some keystrokes.

(In this case, it might make sense to refactor a bit to introduce a `setup` function that allows specifying default options like float window, key mappings, etc.?)

**Comment by TimUntersberger** [comment]
> It'd be nice if one could bypass the main Neogit status window by directly entering, say :Neogit commit (or lua neogit.commit()) to save some keystrokes.

Would you expect the status buffer to be opened with the popup or just the popup?

**Comment by clason** [comment]
Just the popup, I'd say?

**Comment by TimUntersberger** [comment]
You can already this out with your current version by running:

```lua
require('neogit.popups.commit').create() -- replace commit with the kind of popup
```

**Comment by akinsho** [comment]
@TimUntersberger just a heads up re. the example in the docs , there's a bug when calling the `open` function in lua i.e.
```lua
neogit.open() -- <--- This errors since the opts table is missing and is not being defaulted to
-- Inside open think you need a
function M.open(opts)
  opts = opts or {kind = "tab"} -- or something
```

**Comment by TimUntersberger** [comment]
@akinsho fixed. Thank you!
