### ISSUE TITLE
attempt to index global 'popups' (a nil value)

### ISSUE THREAD

**Issue by mfiano** [TimUntersberger/neogit#59]
Hello, it's really a pleasure to see this ambitious project being worked on, being both a VIm and Emacs (at work, not by choice) user and wishing we had something like Magit over here.

I understand this is a WIP project, but after a quick little test I found one small issue. In the status buffer, if and only if the help popup (`?`) is displayed, some of the commands emit an error, such as Log (`L`):
```
E5108: Error executing lua ...ano/.data/nvim/plugins/neogit/lua/neogit/popups/help.lua:38: attempt to index global 'popups' (a nil value)
```

**Comment by RianFuro** [comment]
fixed with 79d1706
