### ISSUE TITLE
Add visual feedback for collapse content

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#67]
As a user I would like to see which content can be toggled without having the manually try `<tab>` and see which content is open/closed.

**Comment by TimUntersberger** [comment]
We should probably copy what magit does with signs (? Idk what to use for this). I think they use arrows by default, but I'd like for this to be configurable.

**Comment by RianFuro** [comment]
Try doing `set foldcolumn=1` inside the neogit status buffer ;)

**Comment by TimUntersberger** [comment]
Can we change what gets used to display the markers? I couldn't find anthing while looking through the docs.

**Comment by akinsho** [comment]
You can set fill chars for the fold column, unfortunately it doesn't support a character at the end. It's under `:h fillchars`.
```
	  foldopen:c	'-'		    mark the beginning of a fold
	  foldclose:c	'+'		    show a closed fold
	  foldsep:c	'│' or '|'      open fold middle marker

```

**Comment by Odie** [comment]
You might want to try `sign_place()`. You can basically put whatever character you want in the gutter area. =)

**Comment by TimUntersberger** [comment]
I added support for this in the latest commit. Should this be enabled by default? I myself feel like the markers are actually unnecessary after implementing them (might be because I have used this plugin a lot).

**Comment by akinsho** [comment]
@TimUntersberger another heads up haven't gotten round to creating an issue yet as I'm a little tight for time today, but I was going to mention that the signs actually go out of sync whilst in use say you incrementally stage several hunks that are open. When you do commit and the hunks are removed some of the signs linger. You then end up with signs not associated with anything.
