### ISSUE TITLE
Can't commit in neovim

### ISSUE THREAD

**Issue by lalitmee** [TimUntersberger/neogit#68]
Getting this error from last update of neogit

![neogit](https://user-images.githubusercontent.com/10762218/112101350-7e17a480-8bcc-11eb-8572-5c5464a917c7.png)

**Comment by TimUntersberger** [comment]
Interesting. I can commit on my machine.

Are you using sessions?

The line that errored tells me that somehow the popup state disappeared. Did you reload some lua code while you had the popup open?

**Comment by carlitux** [comment]
When I try to save the commit message I get this error: `382: Cannot write, 'buftype' option is set` maybe I am doing wrong? how I can save the commit message and continue the commit process.

**Comment by akinsho** [comment]
@carlitux it's different from `fugitive` you don't need to write the buffer. You should try `<c-c><c-c>` instead to commit

**Comment by lalitmee** [comment]
@TimUntersberger , I am using sessions from `vim-startify` nothing else. No I didn't reload the popup or anything. I simply press two times `c` and then it goes to `commit` screen. But that is not happening now.

**Comment by TimUntersberger** [comment]
@lalitmee sessions sometimes create problems for me when using new/updated plugins. 

Could you try commiting in a new repo without using sessions?

**Comment by lalitmee** [comment]
@TimUntersberger , the whole plugin seems broken. 
After the latest update now I can't expand and collapse the hunks.

**Comment by RianFuro** [comment]
@lalitmee that's probably related to #77

**Comment by lalitmee** [comment]
@RianFuro , yeah I was able to fix that by calling the setup function. But I am still not able to write commit messages.

**Comment by TimUntersberger** [comment]
Can you try commiting with only `neogit` installed (so basically nvim + neogit)

**Comment by RianFuro** [comment]
I played around with the sessions from `vim-startify` a bit, but couldn't reproduce the problem. So either it's some specific configuration or has nothing to do with it (or I just missed it, ofc).

**Comment by lalitmee** [comment]
@TimUntersberger , yup you are right. I tried this with only `nvim + neogit` and it worked. I really don't know what is the other thing which is affecting this. Because now I am not even calling the `setup` function. So simply there is not config for `neogit`.

Any idea what other plugin may be affecting this?

**Comment by RianFuro** [comment]
@lalitmee We don't have any other reports of incompatibilities as of yet. You could add back your used plugins one by one and see when neogit starts to break, so we at least know where we need to start looking.

**Comment by lalitmee** [comment]
@RianFuro , this was happening because I was calling the setup function of neogit. I think that was not needed for me. Simply I removed the whole file `neogit.lua` from my config and it worked.

Thank you so much for this awesome plugin. I think it will give a good fight to `fugitive`. :+1:
