### ISSUE TITLE
Neogit autocmd for integration with outside plugins

### ISSUE THREAD

**Issue by DonnieWest** [TimUntersberger/neogit#69]
Use case:

Whenever `neogit` updates the state of `git`, other plugins that deal with `git` need a mechanism to be informed of changes. Otherwise, the state of those plugins become inconsistent with the actual state of the project.

For example, [vim-gitgutter](https://github.com/airblade/vim-gitgutter) will still display code as uncommitted when actually it's been committed with `neogit`

Solution:

Create an autocmd for `neogit` that other plugins (or the user) can use to update those plugins. For example: we already have a `__NeogitStatusRefresh` function. If we expose that as an autocmd it would allow us to do:

`autocmd User NeogitStatusRefresh :GitGutter` to inform `vim-gitgutter` that our project state has changed

**Comment by TimUntersberger** [comment]
that is a cool idea!

**Comment by DonnieWest** [comment]
@TimUntersberger you're awesome! Thanks :)
