### ISSUE TITLE
Showing a diff sometimes crashes vim on windows

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#7]
This is probably an upstream bug. Sometimes toggling a diff for the first time can crash neovim when creating the fold

**Comment by TimUntersberger** [comment]
@bfredl do you know what could cause this? I can sometimes reproduce this 100% (when certain conditions are met, which I don't yet) on windows, but never on linux.

Doing `<from>,<to>fold` is the source of the problem.

I can record a video for you if this could help you.

**Comment by hkupty** [comment]
Same thing happens in linux, fyi.

**Comment by hkupty** [comment]
To me, on linux, it gives me a segfault if I enable diff 3/4 when I have something staged. I'm not sure it's the same issue, but definitely it looks like so.

**Comment by TimUntersberger** [comment]
> To me, on linux, it gives me a segfault if I enable diff 3/4 when I have something staged. I'm not sure it's the same issue, but definitely it looks like so.

Can you reproduce this with a different repo? For me this is happening completely random and I don't know what the problem is.

**Comment by hkupty** [comment]
It happened to me on three different repos, one being this, one being my dotfiles and another is a java codebase. Completely different repos.

**Comment by TimUntersberger** [comment]
Is it always the same position (like 4th staged change or something like that)?

For me it has happend when only 1 file was unstaged or when I had a lot of files open.

**Comment by hkupty** [comment]
1 or more staged, sometimes not even staged, but I guess it's probably something else. Im assuming it's on gits side, when getting the patches, rather than on displaying...

**Comment by TimUntersberger** [comment]
It has to do something with `fold` though. When I remove the folds it doesn't crash anymore. This is overall very weird.

**Comment by hkupty** [comment]
```diff
Modified lua/neogit/status.lua
@@ -59,7 +59,7 @@ local function insert_diff(section, change)
     return
   end
 
-  vim.cmd("normal zd")
+  --vim.cmd("normal zd")
 
   if not change.diff_content then
     if section.name == "staged_changes" then
```
Ok, I've isolated it to this line. When I comment this command, it never breaks for me.

**Comment by hkupty** [comment]
I don't know the intent of this `zd` command, but it *seems* from my manual testing that neogit works well without it.

**Comment by TimUntersberger** [comment]
`zd` deletes the fold under the current line. I honestly don't remember why I delete the fold under the current line. Do you know of any way to get a backtrace for the vim crash? The debug and log features don't really return anything useful for me.

**Comment by hkupty** [comment]
I found that by accident by manually running `zd` and getting an error message (something like no fold to be deleted). Is there a way to check if there's actually a fold there before you run `zd`?

> Do you know of any way to get a backtrace for the vim crash?

Unfortunately no.

Another alternative would be to test without the shorthand version `vim.cmd`, using `vim.api.nvim_command`. this can be helpful to isolate where is the issue.

**Comment by TimUntersberger** [comment]
I just tested without the `zd` and it still crashes for me. I only don't crash when i remove the `create_fold` calls.

**Comment by TimUntersberger** [comment]
Manually doing the `<start>,<end>fold` excommand with the same arguments also crashes neovim for me, so this has to do something with neovim.

**Comment by hkupty** [comment]
Ok, so maybe we're having different issues on Windows and Linux :/

**Comment by TimUntersberger** [comment]
which neovim version are you using?

**Comment by hkupty** [comment]
I've been using master, latest build from today.

**Comment by TimUntersberger** [comment]
@hkupty are you still encountering the issue? I haven't had this bug in a while and thinking about closing this issue.

**Comment by hkupty** [comment]
Been using for a while, didn't seem to happen anymore. I guess it should be safe to close it, sorry for the delay in answering.
