### ISSUE TITLE
Opening nvim on a non git file causes this error

### ISSUE THREAD

**Issue by thepenguinthatwants** [TimUntersberger/neogit#71]
Error executing luv callback:
.../nvim/site/pack/packer/start/neogit/lua/neogit/async.lua:15: ...nvim/site/pack/packer/start/neogit/lua/neogit/status.lua:409: E5560: nvim_command must not be called in a lua loop callback

**Comment by jahn-mtg** [comment]
getting this error as well

**Comment by RianFuro** [comment]
Fixed in 537cc6e

**Comment by thepenguinthatwants** [comment]
NICEEE
