### ISSUE TITLE
Trailing whitespace in Neogit Buffers

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#74]
This is a very minor point 😅 .

Neogit buffers all seem to contain some trailing whitespace in the output. This is evident when using `listchars=trail:-` or some other value.

![image](https://user-images.githubusercontent.com/22454918/112322236-a4127700-8ca8-11eb-95b4-a3ee79c16d97.png)

Ordinarily I'd add this to my `after/ftplugin` but this happens in most of neogit's buffers not all of which have filetypes, and even if they did would be kind of tedious to target all the various buffers to hide the trailing spaces. I don't know if it's just a minor rendering artefact or needed somehow or complicated to remove.

I'd be willing to take a stab at removing them if someone could point me to where they might be being added. Seems likely to be in one spot given it happens in almost every popup

**Comment by RianFuro** [comment]
Should be somewhere here :)
https://github.com/TimUntersberger/neogit/blob/537cc6e1757c41bd75717ebd4421c27b7ebe9205/lua/neogit/lib/popup/lib.lua#L54
