### ISSUE TITLE
Neogit breaks when the `setup` function is not called

### ISSUE THREAD

**Issue by RianFuro** [TimUntersberger/neogit#77]
...with the following error when opening the status buffer:
```
Error executing vim.schedule lua callback: .../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:131: Vim(sign):E155: Unknown sign: NeogitOpen:section
```

**Comment by TimUntersberger** [comment]
Ah this is more of a documentation issue, because calling the setup function is required.

**Comment by RianFuro** [comment]
hmm... could we avoid that? I mean putting `require'neogit'.setup {}` into my config fixes the problem, but then again, if an empty setup is all that's needed we might as well just set sensible defaults without the setup call.

**Comment by akinsho** [comment]
FWIW `require'plugin'.setup()` has become the prevailing convention for nvim lua plugins, so I think this has become quite normal to do and users are becoming quite used to having some sort of setup function, see:
* https://github.com/nvim-telescope/telescope.nvim
* https://github.com/lewis6991/gitsigns.nvim
* https://github.com/norcalli/nvim-colorizer.lua
* https://github.com/phaazon/hop.nvim
etc. 

Butting out now 🚶🏿‍♂️

**Comment by RianFuro** [comment]
Yeah I have no problems with the setup function, I'm just saying we probably shouldn't mandate it to be called if we can avoid it. `telescope` for example works perfectly fine without calling the setup.

Also @akinsho thanks for the reference to `hop`, I was looking for a plugin like that :grin:

**Comment by TimUntersberger** [comment]
We now call the setup function with default arguments when neogit is loaded.
