### ISSUE TITLE
Notification highlights no longer applied

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#79]
Since e321022e02092a63d5f352bd8db89c61ab86ea2d notification highlights no longer seem to be applied. I see they were moved into the `colors/` directory which I'd have assumed would work like `ftplugin` or `syntax` but does not I don't think. I couldn't find much information on it in the docs but from a brief look online at a few plugins it seems that *colorschemes* tend to place their code in that folder but other plugins that apply some highlighting use ftplugin or syntax. Placing the commands in either subdir for neogit in my config re-applies the highlights.

Alternatively this could be an issue related to the colors dir and using `:h packages` but I think this is less likely since my colorscheme which uses that dir works fine.

As another small test I created a `colors` dir in my `&rtp` and it doesn't load the vimscript file in the colors directory.

**Comment by akinsho** [comment]
A little more digging and I think the `colors/` dir is where colorschemes declare themselves rather than where highlight code goes. If I run `colorscheme <tab>` I now see `neogit` listed as a colorscheme

**Comment by RianFuro** [comment]
Git tells me this commit introduced the bug: f8ac2f92 (my first use of `git bisect` :grin:) I'll revert that for now, fixing the structure comes later (I don't know either where to put those highlight-definitions actually... `neogit.vim`? `syntax/<notif-filetype-here>.vim`?)
