### ISSUE TITLE
Could i change the highlight of the unchanged sections?

### ISSUE THREAD

**Issue by hrqmonteiro** [TimUntersberger/neogit#83]
I can change the highlight for the Added and Deleted lines, but can i change the highlight for the unchanged lines?

![2021-03-26_22-34](https://user-images.githubusercontent.com/17055027/112706542-a54bcb80-8e83-11eb-8477-9dd838f7e86b.png)

It's getting the highlight from the "Normal" highlight in the colorscheme, which in my case is this white color, i would very much like to change it for a more greyish tone. Is it possible?

**Comment by RianFuro** [comment]
yeah sure, it's `hi def NeogitDiffContextHighlight <your colors>`

**Comment by hrqmonteiro** [comment]
Yes, that's right!

But that's for when my mouse is on the diff, could i change it for when it is not? Like we have the `NeogitDiffAdd` and `NeogitDiffDelete` ? Or it isn't possible?

**Comment by RianFuro** [comment]
Aah. Nope, not possible, it's just your regular background there, no highlighting.

**Comment by TimUntersberger** [comment]
@RianFuro could be possible right? If we just add `NeogitDiffChange` (or whatever we want to call it) it should work (I think).

**Comment by hrqmonteiro** [comment]
If i new more Lua i would try to implement it, and request a PR, but unfortunately i only use it to configure Nvim so i know very little 😬

**Comment by RianFuro** [comment]
@TimUntersberger It's definitely possible to do. Easiest solution would be to just put signs with line-highlignting on all the normal diff rows too. I worry a bit about performance in that case, but from what I tested with the context highlighting, even that should be fine given reasonable sized change sets (and it only happens on redraw too).

Other than that, doing it with pure syntax matching could work, but could also be very tricky.

**Comment by RianFuro** [comment]
@hrqmonteiro If you wanna give it a shot, it's not that involved; you just have to copy and extend what's there already.
Define a new highlight group and sign here:
https://github.com/TimUntersberger/neogit/blob/4689f716a97b3ec5c135ff9eac513974acb18cdc/syntax/NeogitStatus.vim#L43-L57

Then place that sign for normal diff lines (not matching hunk headers, diff-add or diff-delete) here:
https://github.com/TimUntersberger/neogit/blob/4689f716a97b3ec5c135ff9eac513974acb18cdc/lua/neogit/status.lua#L195-L212

Then do some tests with reasonable and very large change sets and check if the performance holds up when redrawing the buffer.

**Comment by hrqmonteiro** [comment]
I forked and implemented, you can see [here](https://github.com/hrqmonteiro/neogit/blob/be3851120ee2762686d1dc58cbbd460e752466cf/syntax/NeogitStatus.vim#L45) and [here](https://github.com/hrqmonteiro/neogit/blob/be3851120ee2762686d1dc58cbbd460e752466cf/lua/neogit/status.lua#L157) please.

Well, it is working fine:

![2021-03-27_11-18](https://user-images.githubusercontent.com/17055027/112723645-6bfc7580-8eee-11eb-9c58-4c8ad26103da.png)

And i tried with the large change sets that i could have on my machine, and the performance was the same as before, idk if larger sets would have some difference in performance, but here went fine.

**Comment by RianFuro** [comment]
@hrqmonteiro just open a pr, I'll take a look later :)
