### ISSUE TITLE
Allow to see and navigate a commit’s hunk

### ISSUE THREAD

**Issue by phaazon** [TimUntersberger/neogit#89]
For instance, in the log view, it would be cool to do what magit does by showing the hunks and allow to do actions with them (like add to staging area / working dir, etc.). Example from magit:

![Screenshot_20210328_161715](https://user-images.githubusercontent.com/506592/112755464-1b197980-8fe1-11eb-819e-870cce5631fa.png)
![Screenshot_20210328_161725](https://user-images.githubusercontent.com/506592/112755466-1ce33d00-8fe1-11eb-8e05-1286ee083335.png)

**Comment by TimUntersberger** [comment]
How did you get to the right view? Did you just press `<tab>` on a commit and it expanded inside the view to this or is it something completely separate?

**Comment by RianFuro** [comment]
@TimUntersberger This is simply opening the log view in magit (`ll` from the status view for example) and then pressing `enter` on a commit.

**Comment by phaazon** [comment]
Yeah, `return` on a commit. You get that from the log or, like in this image, the “Recent commits” view of the status page.

**Comment by TimUntersberger** [comment]
@phaazon could you please checkout the PR and give me some feedback? Not too sure whether the performance is acceptable.
