### ISSUE TITLE
Committing does not work for git worktrees

### ISSUE THREAD

**Issue by weilbith** [TimUntersberger/neogit#90]
I must admit that I'm not 100% about this. I just started to use this plugin. On repositories which have no commit hooks, I can nicely commit as expected. But when there are such hooks I observe the following:
When I type `cc` in the status window to start a commit, I get the error `Error executing vim.schedule lua callback: ...site/pack/packer/opt/neogit/lua/neogit/popups/commit.lua:20: Vim(write):E212: Can't open file for writing: not
a directory`.  If I then hit `return` I still get the commit message window. But as a result of the former error on save the error `E212: Can't open file for writing: not a directory` occurs.
I must admit I'm not too sure why the Lua function fails. But could it be that it does not expect the hooks to execute? On fugitive I was seeing the shell output of the pre-commit hooks and once done I could type my commit message. If a hook failed I got navigated back to the status window and the message was printed.
So atm this is a blocker for me to finally make the cut and use Neogit exclusively over Fugitive.

**Comment by RianFuro** [comment]
Hmm, this is too early for the commit hook, we're not calling anything git-related up to that point.

Wild guess: what's your `cwd`? The error looks like it can't find the path to open the commit message file

**Comment by weilbith** [comment]
Do you mean `pwd`? Then it is just the absolute path of the local repositories root directory. 🤷🏾

**Comment by weilbith** [comment]
What comes into my mind: this repo also has multiple worktrees locally. So `git worktree list` has three entries. This is the same (not the exact number) for other repositories. Is that an issue for the  `.git` directory?

**Comment by RianFuro** [comment]
Yeah that could be an issue. We do a poor job so far with non-standard project setups; if the worktree, repository root and current working directory don't align, things generally don't work yet.

**Comment by weilbith** [comment]
It shouldn't be too hard to fix this. In a worktree, `.git a is a file that includes the absolute path to the root worktree and there the worktree git directory for this worktree. So for example The main repo is at `/home/user/projects/foo` and a worktree of it is in `/home/user/projects/foo-prs`, then the `.git` filesystem entry in the latter repo is a file that includes `/home/user/projects/foo/.git/worktree/foo-prs`.

**Comment by TimUntersberger** [comment]
@weilbith can you please execute the following code and tell me whether this prints the correct path?

```lua

local a = require('neogit.async')
a.dispatch(function()
  print(a.wait(require("neogit.lib.git.cli").git_root()))
end)

```

**Comment by weilbith** [comment]
I tried to run it with

```vim
:lua require('neogit.async').dispatch(function() print(require('neogit.async').wait(require('neogit.lib.git.cli').git_root())) end)
```

But this gives me the following error:

```
E5108: Error executing lua ...im_test_site/pack/packer/opt/neogit/lua/neogit/async.lua:73: ...t_site/pack/packer/opt/neogit/lua/neogit/lib/git/cli.lua:417: unknown field
```

**Comment by TimUntersberger** [comment]
Try updating the plugin.

**Comment by weilbith** [comment]
Okay that worked. Okay so now the question what it the correct path? It gives me the path of the current local repository where my worktree is placed. So not the "origin" local repository where all worktrees point to. So this path + `./git` is still this worktree file not a directory with the database etc.

**Comment by TimUntersberger** [comment]
Does the latest version fix this for you or changes anyting @weilbith?

**Comment by weilbith** [comment]
Perfect. It works. Thank you very much! 🙏🏾 
Finally I can use this plugin again. 😬

**Comment by TimUntersberger** [comment]
@weilbith did you reopen this on purpose?

**Comment by weilbith** [comment]
Yes. Sorry, re-opened it quite fast when I observed the wrong behavior. But I wanted to test it again to verify it. Sorry. I'll check it again soonish.
The issue I think is that it tries to do the commit always in the main git worktree and not the current active one. I discovered that because the commit fails with the error that the commit is empty. But I had staged files. On the other worktree I had nothing staged.
I need so test it with a reproducable instructions. But it happened during work and I was a little stressed/under heavy load.

**Comment by weilbith** [comment]
Sorry, forgot the final comment;
Yes, NeoGit always tries to commit in the main worktree. That is an issue..

**Comment by disrupted** [comment]
> Sorry, forgot the final comment;
> Yes, NeoGit always tries to commit in the main worktree. That is an issue..

Hm, this is working for me. Did you check what it says in the git command history ($)? Here it picks up the correct worktree: `git commit --file=[...]repo.git/worktrees/feature-xy/NEOGIT_COMMIT_EDITMSG`

**Comment by weilbith** [comment]
Yes, I did check it. The bottom line of the issue is `no changes added to commit (use "git add" and/or "git commit -a")` (plus a current `git status` output). Already in the commit message window I don't see any staged changes.

**Comment by weilbith** [comment]
If I open NeoGit, it shows me my staged changes. If I run `:pwd` this is correctly the worktree. If I run `:!git status` this is the same. If I now go into the commit message window and run `:pwd' it switched to main worktree. The `:!git status` check here also shows now a different status.

**Comment by TimUntersberger** [comment]
When we commit we don't use the `cwd` of neovim.

We use the path from `git rev-parse --git-dir`

**Comment by weilbith** [comment]
Well, so this then results into the subpath of the main worktree. Like that: `..../project-main-worktree/.git/worktrees/project-other-worktree`.

**Comment by weilbith** [comment]
Okay here are instructions from zero to reproduce the issue.

Preparation (`HEAD` must refer to a commit to be able to create a worktree, therefore the first commit is necessary):

```sh
$ cd $(mktemp --directory)
$ mkdir project-main
$ cd project-main
$ echo 'foo' > bar.txt
$ git init .
$ git add bar.txt
$ git commit --message="add bar"
$ git worktree add ../project-prs
$ cd ../project-prs
```

Now create a new file with `nvim foo.txt`, add some content and save it. Now open `:NeoGit` and stage `foo.txt`. Go for a commit `cc`, write a message, save it and confirm to finalize the commit.

You should get the notification that there was an error. Open the command history, to to the bottom and open it `$Gzo`. You should see the message I wrote above.

**Comment by TimUntersberger** [comment]
@weilbith just tried this and it works for me.

**Comment by RianFuro** [comment]
@weilbith do you maybe have `autochdir` set? This currently causes some problems when opening the commit buffer, as the cwd then changes and we currently can't handle that :sweat_smile: 
See https://github.com/TimUntersberger/neogit/issues/109#issuecomment-820687032
Afaik we disable `autochdir` on our own buffers, but not the commit buffer, right?

**Comment by TimUntersberger** [comment]
@RianFuro we disable the autochdir until the status buffer is closed again. This shouldn't cause issues though, because we are using the git dir from`git rev-parse --git-dir`. 

When @weilbith executes the command he gets a path similiar to mine so I think this can't be the problem. I really have no idea anymore what this could be.

**Comment by weilbith** [comment]
Thank you very much for your help guys! 🙏🏾 
The hint in regards of `autochdir` was the hint I needed. The issue is a plugin I use called [vim-rooter](https://github.com/airblade/vim-rooter). If I disable it, I was able to run through my above example successfully twice in a row. So it was my setups fault. I'm very sorry. I'll see how I can configure the mentioned plugin to work with NeoGit.
Thank you very much!
