### ISSUE TITLE
Commit fails when cwd is not the repo root

### ISSUE THREAD

**Issue by ruifm** [TimUntersberger/neogit#91]
# Steps to reproduce

```bash
mkdir testrepo && cd testrepo
git init
mkdir foo && cd foo
touch bar && git add bar
nvim +"lua require'neogit'.open({ 'commit' })" +"norm c"
```

The following error message shows up:

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/neogit/lua/neogit/popups/commit.lua:20: Vim(write):E212: Can't open file for writing: no such file or directory
```

The commit window still opens and I can edit it, but when doing `:write` it fails with:

```
".git/NEOGIT_COMMIT_EDITMSG"
E212: Can't open file for writing: no such file or directory
```

This looks like `neogit` is expecting the `.git` directory to be directly acessible from the cwd, when that is necessarily not the case:

https://github.com/TimUntersberger/neogit/blob/2f504fcf734ddb6b281a93e01782ecb0dae0774e/lua/neogit/popups/commit.lua#L9

# Possible solutions

* Internally change `cwd` when calling `neogit.open({ "commit" })` (maybe using `lcd`?)
* Make neogit directly open `<project_root>/.git/COMMIT_EDITMSG` (this looks like the better long term option to me since it does not require changing any cwd)

Fugitive does not have this issue.

# Use case: why would one ever want to do this?

In big repositories (like monorepos), it's often not pratical always work from the project root due to the huge amount of unrelated files which just clutter and slow down fuzzy-finding tools.

Meanwhile, is there any config workarround I can use?

## Edit

Possibly related: https://github.com/TimUntersberger/neogit/issues/90

**Comment by ronisbr** [comment]
I am also having this problem. Is there any workaround ?

**Comment by ruifm** [comment]
> I am also having this problem. Is there any workaround ?

@ronisbr the linked PR https://github.com/TimUntersberger/neogit/pull/94 solves the issue for me

**Comment by ruifm** [comment]
I just wanted to add that not only commiting is broken, opening buffers from `neogit`'s display using `<cr>` also fails when cwd is not the repo root.

Even #94 does not solve that.

**Comment by kamalmarhubi** [comment]
Drive-by, but one should not assume that `.git` exists at the top-level (since you can set `GIT_DIR` to any path), or that it is a directory (if using [worktree]s). The best thing to do is to run `git rev-parse --git-dir` to have git tell you where it is.

[worktree]: https://git-scm.com/docs/git-worktree

**Comment by itmecho** [comment]
Until this gets fixed, I added this autocmd as a workaround:
```vim
autocmd FileType NeogitStatus lcd <path to root>
```

As part of my local dev setup I have an env var with that path in it so I just use that. If you need to get it dynamically, you can use the following based off of @kamalmarhubi's comment:

```lua
local git_root = vim.fn.system("git rev-parse --git-dir"):gsub("/.git", "")
```

**Comment by TimUntersberger** [comment]
Is this fixed for you guys?

**Comment by andersevenrud** [comment]
I've been using this since the patches was applied, and I haven't run into any problems yet.

**Comment by TimUntersberger** [comment]
Closing this because of positive feedback.
