### ISSUE TITLE
Autoread buffers

### ISSUE THREAD

**Issue by timsofteng** [TimUntersberger/neogit#93]
Hello.
Imagine I do something in file and then reject this changes in Neogit  by pressing `x`. Then I close neogit and return to this file. Unfortunately buffer is same as it was before the reject. I expect it should contain changes which I did in Neogit. 

Could it be fixed?

**Comment by RianFuro** [comment]
Huh, good point well made. I assume we could check if there is a buffer to the file the discarded hunk belongs to and reload it.

As a workaround, `:e` should reload the buffer from disk, which should include the discard just made.

**Comment by timsofteng** [comment]
Thanks!

Yep, I know about `:e` but I find it slightly annoying. In addition it can trigger some weird error if you forget to do it and try to modify and save buffer.

**Comment by oberblastmeister** [comment]
We could also wait until fswatch autoread is merged in core https://github.com/neovim/neovim/pull/12593

**Comment by TimUntersberger** [comment]
This is semi fixed in the latest version.

After discarding we now call the checktime command `:h checktime`

**Comment by TimUntersberger** [comment]
@timsofteng pls tell me if this is fixed for you.

**Comment by timsofteng** [comment]
> @timsofteng pls tell me if this is fixed for you.

Yep. Looks like it works now. Thanks!
