### ISSUE TITLE
NeoGitStatus does not respect number

### ISSUE THREAD

**Issue by bigjazzsound** [TimUntersberger/neogit#95]
Opening a NeogitStatus buffer does not respect if number is set. Any subsequent buffer opened with GoToFile does not have number set.

**Comment by akinsho** [comment]
You can create a ftplugin for NeogitStatus in your `after/ftplugin` directory and change the vim settings to your preference.

**Comment by RianFuro** [comment]
We do have a real problem here though: we should set `nonumber` and `norelativenumber` as local instead of global options on the buffer; otherwise, when opening a buffer while having the status buffer in focus will open the new buffer with the same settings, ignoring user settings.

**Comment by TimUntersberger** [comment]
Don't we already set it as buffer local? Isn't the problem that the settings carry over in the same split? (Might just remember this incorrectly though)

**Comment by RianFuro** [comment]
https://github.com/TimUntersberger/neogit/blob/2f504fcf734ddb6b281a93e01782ecb0dae0774e/lua/neogit/lib/buffer.lua#L224-L225

**Comment by TimUntersberger** [comment]
> 
> 
> https://github.com/TimUntersberger/neogit/blob/2f504fcf734ddb6b281a93e01782ecb0dae0774e/lua/neogit/lib/buffer.lua#L224-L225

well rip

**Comment by TimUntersberger** [comment]
@bigjazzsound is this fixed for you?

**Comment by bigjazzsound** [comment]
It is. Thank you!
