### ISSUE TITLE
possible to integrate delta?

### ISSUE THREAD

**Issue by alok** [TimUntersberger/neogit#97]
https://github.com/dandavison/delta

an amazing diff viewer if you can make it work

**Comment by TimUntersberger** [comment]
How would you expect the integration to work?

**Comment by jebaum** [comment]
I'm guessing the feature alok really wants, which I think would be nice as well, is syntax highlighting of the content of diffs. Whether delta is the best tool to provide this within neovim is another question, and I don't know the answer.

The obvious challenge there that I can think of is that the neogit buffer in which you can expand diffs can have any number of various different languages in it.

**Comment by stumash** [comment]
tree-sitter is a possible integration here. `Telescope` uses it to syntax-highlight file previews for its fuzzy file search. That could probably be achieved here.

Just a thought

**Comment by kellpossible** [comment]
@TimUntersberger this is marked as completed, how do we use it?

**Comment by TimUntersberger** [comment]
@kellpossible don't really remember why I closed it, but this is isn't implemented. I guess I closed it, because I didn't plan on doing it? I think the "close as completed" is the default for old issues.

**Comment by tednaaa** [comment]
Would be awesome to have delta integration

and maybe tree-sitter..?

**Comment by stevenxxiu** [comment]
@CKolkey Any chance of reopening this? For me this will make *neogit* competitive with *lazygit*. I enjoy using *neogit* a lot more, for its keybinds and as I can edit text directly in *Neovim*.

**Comment by CKolkey** [comment]
Do you mind elaborating on what aspect of delta would be a good addition?

**Comment by stevenxxiu** [comment]
> Do you mind elaborating on what aspect of delta would be a good addition?

Compared to the current *neogit*, here are some things I like about using *delta* as a diff viewer in *LazyGit*:

- Side-by-side view. Exists in *diffview*.
- Syntax highlighting. Exists in *diffview*.
- Show symlinks. Doesn't exist in *diffview*.
- Clearly shows which files get renamed to which. Doesn't exist in *diffview*.

*diffview* is the closest experience, but it also has the downsides that I need to press `d` first, and that I need to go through each file to see the changes. *LazyGit* simply shows all the diffs in one screen. This is closer to *Git*'s diff.
